/*
 * FF3 Decompiled Functions - Pathfinding & Map Names
 * Generated by Ghidra headless analysis
 * Program: GameAssembly.dll
 * Image Base: 0x180000000
 * IL2CPP types applied: True
 */


/********************************************************************/
/* FieldController$$GetMapTitleID
 * RVA: 0x27FED0
 * Address: 0x18027FED0
 *******************************************************************/


undefined8 FieldController_GetMapTitleID(longlong param_1)

{
  return *(undefined8 *)(param_1 + 0x150);
}



/********************************************************************/
/* MapModel$$GetMapName
 * RVA: 0x3104C0
 * Address: 0x1803104C0
 *******************************************************************/


longlong FUN_1803104c0(longlong param_1)

{
  longlong lVar1;
  
  lVar1 = *(longlong *)(param_1 + 0x40);
  if (lVar1 != 0) {
    return *(longlong *)(lVar1 + 0x18);
  }
  return lVar1;
}



/********************************************************************/
/* External.Misc$$ShowMapTitle
 * RVA: 0x9391D0
 * Address: 0x1809391D0
 *******************************************************************/


/* WARNING: Globals starting with '_' overlap smaller symbols at the same address */

void FUN_1809391d0(longlong param_1)

{
  undefined8 uVar1;
  undefined8 uVar2;
  code *pcVar3;
  longlong lVar4;
  longlong lVar5;
  undefined8 uVar6;
  longlong *plVar7;
  
  if (DAT_181fefcd0 == '\0') {
    thunk_FUN_180203190(DAT_1817e5220);
    DAT_181fefcd0 = '\x01';
  }
  if (param_1 != 0) {
    lVar4 = FUN_180cb7e40(param_1,0);
    if ((lVar4 != 0) && (lVar4 = *(longlong *)(lVar4 + 0x20), lVar4 != 0)) {
      if (*(int *)(lVar4 + 0x18) == 0) {
        uVar6 = thunk_FUN_1801f9600();
        FUN_18023bce0(uVar6,0);
        pcVar3 = (code *)swi(3);
        (*pcVar3)();
        return;
      }
      uVar6 = *(undefined8 *)(lVar4 + 0x20);
      lVar4 = FUN_180cb7e40(param_1,0);
      if ((lVar4 != 0) && (lVar4 = *(longlong *)(lVar4 + 0x20), lVar4 != 0)) {
        if (*(uint *)(lVar4 + 0x18) < 2) {
          uVar6 = thunk_FUN_1801f9600();
          FUN_18023bce0(uVar6,0);
          pcVar3 = (code *)swi(3);
          (*pcVar3)();
          return;
        }
        uVar1 = *(undefined8 *)(lVar4 + 0x28);
        if (((*(byte *)(DAT_1822ecd58 + 0x12f) & 2) != 0) && (*(int *)(DAT_1822ecd58 + 0xe0) == 0))
        {
          il2cpp_runtime_class_init(DAT_1822ecd58);
        }
        lVar4 = *(longlong *)(*(longlong *)(DAT_1822ecd58 + 0xb8) + 0x18);
        if (lVar4 != 0) {
          FUN_180317020(lVar4,uVar6,uVar1,0);
          if (((*(byte *)(DAT_1822fc008 + 0x12f) & 2) != 0) && (*(int *)(DAT_1822fc008 + 0xe0) == 0)
             ) {
            il2cpp_runtime_class_init();
          }
          lVar4 = FUN_180f6c390(DAT_1822d9688);
          if (((*(byte *)(DAT_1822ecc10 + 0x12f) & 2) != 0) && (*(int *)(DAT_1822ecc10 + 0xe0) == 0)
             ) {
            il2cpp_runtime_class_init(DAT_1822ecc10);
          }
          lVar5 = *(longlong *)(*(longlong *)(DAT_1822ecc10 + 0xb8) + 0x20);
          if (lVar5 == 0) {
            if (((*(byte *)(DAT_1822ecc10 + 0x12f) & 2) != 0) &&
               (*(int *)(DAT_1822ecc10 + 0xe0) == 0)) {
              il2cpp_runtime_class_init(DAT_1822ecc10);
            }
            uVar2 = **(undefined8 **)(DAT_1822ecc10 + 0xb8);
            lVar5 = thunk_FUN_180207de0(DAT_1822b28b0);
            FUN_1802e9aa0(lVar5,uVar2,DAT_1822d1010,0);
            plVar7 = (longlong *)(*(longlong *)(DAT_1822ecc10 + 0xb8) + 0x20);
            *plVar7 = lVar5;
            thunk_FUN_180239040(plVar7,lVar5);
          }
          if (lVar4 != 0) {
            FUN_180923b30(lVar4,_DAT_181b577c8,lVar5,0);
            if (((*(byte *)(DAT_1822fc4e0 + 0x12f) & 2) != 0) &&
               (*(int *)(DAT_1822fc4e0 + 0xe0) == 0)) {
              il2cpp_runtime_class_init();
            }
            lVar4 = FUN_180645130(0);
            if (lVar4 != 0) {
              FUN_180646de0(lVar4,uVar6,0);
              lVar4 = FUN_180645130(0);
              if (lVar4 != 0) {
                FUN_180646e10(lVar4,uVar1,0);
                FUN_180380080(0);
                return;
              }
            }
          }
        }
      }
    }
  }
  FUN_18023bd10();
  pcVar3 = (code *)swi(3);
  (*pcVar3)();
  return;
}



/********************************************************************/
/* Map$$get_MapName
 * RVA: 0xA87AA0
 * Address: 0x180A87AA0
 *******************************************************************/


undefined8 FUN_180a87aa0(longlong param_1)

{
  longlong lVar1;
  code *pcVar2;
  undefined8 uVar3;
  
  lVar1 = *(longlong *)(param_1 + 0x10);
  if (lVar1 == 0) {
    FUN_18023bd10();
    pcVar2 = (code *)swi(3);
    uVar3 = (*pcVar2)();
    return uVar3;
  }
  if (*(int *)(lVar1 + 0x18) != 0) {
    return *(undefined8 *)(lVar1 + 0x20);
  }
  uVar3 = thunk_FUN_1801f9600();
  FUN_18023bce0(uVar3,0);
  pcVar2 = (code *)swi(3);
  uVar3 = (*pcVar2)();
  return uVar3;
}



/********************************************************************/
/* Map$$get_MapTitle
 * RVA: 0xA8A1B0
 * Address: 0x180A8A1B0
 *******************************************************************/


undefined8 FUN_180a8a1b0(longlong param_1)

{
  longlong lVar1;
  code *pcVar2;
  undefined8 uVar3;
  
  lVar1 = *(longlong *)(param_1 + 0x10);
  if (lVar1 == 0) {
    FUN_18023bd10();
    pcVar2 = (code *)swi(3);
    uVar3 = (*pcVar2)();
    return uVar3;
  }
  if (2 < *(uint *)(lVar1 + 0x18)) {
    return *(undefined8 *)(lVar1 + 0x30);
  }
  uVar3 = thunk_FUN_1801f9600();
  FUN_18023bce0(uVar3,0);
  pcVar2 = (code *)swi(3);
  uVar3 = (*pcVar2)();
  return uVar3;
}



/********************************************************************/
/* MapRouteSearcher$$CanIgnore
 * RVA: 0xC4E970
 * Address: 0x180C4E970
 *******************************************************************/


undefined4
MapRouteSearcher__CanIgnore(longlong param_1,longlong param_2,int param_3,int param_4,int param_5)

{
  code *pcVar1;
  int iVar2;
  undefined4 uVar3;
  
  if (-1 < param_4) {
    if (param_1 == 0) {
LAB_180c4e9d0:
      FUN_18023bd10();
      pcVar1 = (code *)swi(3);
      uVar3 = (*pcVar1)();
      return uVar3;
    }
    if (param_4 < *(int *)(param_1 + 0x18)) {
      if ((((-1 < param_5) && (param_5 < *(int *)(param_1 + 0x1c))) && (-1 < param_3)) &&
         (param_3 < *(int *)(param_1 + 0x20))) {
        if (param_2 == 0) goto LAB_180c4e9d0;
        iVar2 = FUN_180156650(param_2,(longlong)param_3,(longlong)param_4,(longlong)param_5);
        if (iVar2 == 0) {
          return 0;
        }
      }
    }
  }
  return 1;
}



/********************************************************************/
/* MapRouteSearcher$$EntityWorldPositionToCellPosition
 * RVA: 0xC4E9E0
 * Address: 0x180C4E9E0
 *******************************************************************/


undefined8 *
MapRouteSearcher__EntityWorldPositionToCellPosition
          (undefined8 *param_1,longlong *param_2,longlong param_3)

{
  undefined8 uVar1;
  undefined4 uVar2;
  code *pcVar3;
  int iVar4;
  longlong lVar5;
  undefined8 *puVar6;
  ushort uVar7;
  undefined8 local_38;
  undefined4 local_30;
  undefined local_28 [32];
  
  if (DAT_181ff1ac2 == '\0') {
    thunk_FUN_180203190(DAT_1817dfb38);
    DAT_181ff1ac2 = '\x01';
  }
  *param_1 = 0;
  *(undefined4 *)(param_1 + 1) = 0;
  if (param_3 != 0) {
    lVar5 = FUN_181105ce0(param_3,0);
    if (lVar5 != 0) {
      puVar6 = (undefined8 *)FUN_18154a2b0(&local_38,lVar5,0);
      if (param_2 != (longlong *)0x0) {
        lVar5 = *param_2;
        uVar7 = 0;
        uVar2 = *(undefined4 *)(puVar6 + 1);
        uVar1 = *puVar6;
        if (*(ushort *)(lVar5 + 0x126) != 0) {
          do {
            if (*(longlong *)(*(longlong *)(lVar5 + 0xb0) + (ulonglong)uVar7 * 0x10) ==
                DAT_1822fc9e0) {
              puVar6 = (undefined8 *)
                       (((ulonglong)
                         (*(int *)(*(longlong *)(lVar5 + 0xb0) + 8 + (ulonglong)uVar7 * 0x10) + 4) +
                        0x13) * 0x10 + lVar5);
              goto LAB_180c4eaae;
            }
            uVar7 = uVar7 + 1;
          } while (uVar7 < *(ushort *)(lVar5 + 0x126));
        }
        puVar6 = (undefined8 *)FUN_1801f9690(param_2,DAT_1822fc9e0,4);
LAB_180c4eaae:
        local_38 = uVar1;
        local_30 = uVar2;
        puVar6 = (undefined8 *)(*(code *)*puVar6)(local_28,param_2,&local_38,puVar6[1]);
        uVar2 = *(undefined4 *)(puVar6 + 1);
        *param_1 = *puVar6;
        *(undefined4 *)(param_1 + 1) = uVar2;
        lVar5 = FUN_181105ca0(param_3,0);
        if (lVar5 != 0) {
          iVar4 = FUN_181109d50(lVar5,0);
          *(float *)(param_1 + 1) = (float)(iVar4 + -9);
          return param_1;
        }
      }
    }
  }
  FUN_18023bd10();
  pcVar3 = (code *)swi(3);
  puVar6 = (undefined8 *)(*pcVar3)();
  return puVar6;
}



/********************************************************************/
/* MapRouteSearcher$$MakeRouteMapWithCollision
 * RVA: 0xC4EB40
 * Address: 0x180C4EB40
 *******************************************************************/


longlong MapRouteSearcher__MakeRouteMapWithCollision(longlong param_1)

{
  int iVar1;
  int iVar2;
  int iVar3;
  int iVar4;
  code *pcVar5;
  int iVar6;
  longlong lVar7;
  longlong lVar8;
  int iVar9;
  int iVar10;
  int iVar11;
  longlong local_48;
  longlong local_40;
  longlong local_38;
  
  if (DAT_181ff1ac3 == '\0') {
    thunk_FUN_180203190(DAT_1817dfb60);
    DAT_181ff1ac3 = '\x01';
  }
  if (param_1 == 0) {
    FUN_18023bd10();
    pcVar5 = (code *)swi(3);
    lVar7 = (*pcVar5)();
    return lVar7;
  }
  local_48 = (longlong)*(int *)(param_1 + 0x20);
  local_40 = (longlong)*(int *)(param_1 + 0x18);
  local_38 = (longlong)*(int *)(param_1 + 0x1c);
  lVar7 = FUN_18023b8f0(DAT_1822c8930,&local_48);
  iVar1 = *(int *)(param_1 + 0x40);
  iVar2 = *(int *)(param_1 + 0x44);
  iVar10 = 0;
  do {
    if (*(int *)(param_1 + 0x20) <= iVar10) {
      return lVar7;
    }
    iVar3 = *(int *)(param_1 + 0x18);
    iVar11 = 0;
    if (0 < iVar3) {
      do {
        iVar4 = *(int *)(param_1 + 0x1c);
        iVar9 = 0;
        if (0 < iVar4) {
          do {
            if (*(longlong *)(param_1 + 0x10) == 0) {
LAB_180c4ecb3:
              FUN_18023bd10();
              pcVar5 = (code *)swi(3);
              lVar7 = (*pcVar5)();
              return lVar7;
            }
            lVar8 = FUN_1800ddc20(*(longlong *)(param_1 + 0x10),iVar10,DAT_1822a64a0);
            if (lVar8 == 0) goto LAB_180c4ecb3;
            iVar6 = FUN_1800dcca0(lVar8,(longlong)(iVar11 + iVar1),(longlong)(iVar2 + iVar9));
            if (lVar7 == 0) goto LAB_180c4ecb3;
            FUN_1801566c0(lVar7,(longlong)iVar10,iVar11,iVar9,(iVar6 != 0) - 1);
            iVar9 = iVar9 + 1;
          } while (iVar9 < iVar4);
        }
        iVar11 = iVar11 + 1;
      } while (iVar11 < iVar3);
    }
    iVar10 = iVar10 + 1;
  } while( true );
}



/********************************************************************/
/* MapRouteSearcher$$MakeRouteMapWithoutCollision
 * RVA: 0xC4ECC0
 * Address: 0x180C4ECC0
 *******************************************************************/


longlong MapRouteSearcher__MakeRouteMapWithoutCollision(longlong param_1)

{
  code *pcVar1;
  longlong lVar2;
  int iVar3;
  int iVar4;
  int iVar5;
  longlong local_38;
  longlong local_30;
  longlong local_28;
  
  if (DAT_181ff1ac4 == '\0') {
    thunk_FUN_180203190(DAT_1817dfb64);
    DAT_181ff1ac4 = '\x01';
  }
  if (param_1 != 0) {
    local_38 = (longlong)*(int *)(param_1 + 0x20);
    local_30 = (longlong)*(int *)(param_1 + 0x18);
    local_28 = (longlong)*(int *)(param_1 + 0x1c);
    lVar2 = FUN_18023b8f0(DAT_1822c8930,&local_38);
    iVar5 = 0;
    do {
      if (*(int *)(param_1 + 0x20) <= iVar5) {
        return lVar2;
      }
      for (iVar4 = 0; iVar4 < *(int *)(param_1 + 0x18); iVar4 = iVar4 + 1) {
        for (iVar3 = 0; iVar3 < *(int *)(param_1 + 0x1c); iVar3 = iVar3 + 1) {
          if (lVar2 == 0) {
            FUN_18023bd10();
            pcVar1 = (code *)swi(3);
            lVar2 = (*pcVar1)();
            return lVar2;
          }
          FUN_1801566c0(lVar2,(longlong)iVar5,(longlong)iVar4,(longlong)iVar3,0);
        }
      }
      iVar5 = iVar5 + 1;
    } while( true );
  }
  FUN_18023bd10();
  pcVar1 = (code *)swi(3);
  lVar2 = (*pcVar1)();
  return lVar2;
}



/********************************************************************/
/* MapRouteSearcher$$SearchAroundCellWithCollision
 * RVA: 0xC4EDC0
 * Address: 0x180C4EDC0
 *******************************************************************/


undefined8
MapRouteSearcher_SearchAroundCellWithCollision
          (undefined8 param_1,longlong param_2,uint param_3,int param_4,int param_5,
          undefined4 param_6)

{
  undefined4 uVar1;
  longlong lVar2;
  longlong lVar3;
  code *pcVar4;
  undefined4 uVar5;
  char cVar6;
  int iVar7;
  int iVar8;
  uint uVar9;
  uint uVar10;
  undefined8 *puVar11;
  undefined8 uVar12;
  uint uVar13;
  int iVar14;
  longlong lVar15;
  int iVar16;
  uint uVar17;
  uint uVar18;
  longlong lVar19;
  undefined8 uStack_98;
  undefined4 uStack_90;
  undefined8 uStack_88;
  undefined4 uStack_80;
  undefined8 uStack_78;
  undefined4 uStack_70;
  undefined auStack_68 [48];
  
  lVar19 = (longlong)(int)param_3;
  if (DAT_181ff1ac5 == '\0') {
    thunk_FUN_180203190(DAT_1817dfb80);
    DAT_181ff1ac5 = '\x01';
  }
  if ((param_2 != 0) && (lVar15 = *(longlong *)(param_2 + 0x10), lVar15 != 0)) {
    if (*(uint *)(lVar15 + 0x18) <= param_3) {
      FUN_180d9d940(0);
    }
    lVar15 = *(longlong *)(*(longlong *)(lVar15 + 0x10) + 0x20 + lVar19 * 8);
    if (lVar15 != 0) {
      uVar18 = param_5 + *(int *)(param_2 + 0x44);
      uVar13 = *(int *)(param_2 + 0x40) + param_4;
      if (**(uint **)(lVar15 + 0x10) <= uVar13) {
        uVar12 = thunk_FUN_1801f9600();
        FUN_18023bce0(uVar12,0);
        pcVar4 = (code *)swi(3);
        uVar12 = (*pcVar4)();
        return uVar12;
      }
      lVar2 = *(longlong *)(*(uint **)(lVar15 + 0x10) + 4);
      if ((uint)lVar2 <= uVar18) {
        uVar12 = thunk_FUN_1801f9600();
        FUN_18023bce0(uVar12,0);
        pcVar4 = (code *)swi(3);
        uVar12 = (*pcVar4)();
        return uVar12;
      }
      lVar3 = *(longlong *)(param_2 + 0x10);
      uVar13 = *(uint *)(lVar15 + 0x20 + ((int)uVar13 * lVar2 + (longlong)(int)uVar18) * 4);
      if (lVar3 != 0) {
        if (*(uint *)(lVar3 + 0x18) <= param_3) {
          FUN_180d9d940(0);
        }
        lVar15 = *(longlong *)(*(longlong *)(lVar3 + 0x10) + 0x20 + lVar19 * 8);
        if (lVar15 != 0) {
          uVar18 = 1;
          iVar7 = thunk_FUN_1801db2d0(lVar15,1,0);
          lVar15 = *(longlong *)(param_2 + 0x10);
          if (lVar15 != 0) {
            if (*(uint *)(lVar15 + 0x18) <= param_3) {
              FUN_180d9d940(0);
            }
            lVar19 = *(longlong *)(*(longlong *)(lVar15 + 0x10) + 0x20 + lVar19 * 8);
            if (lVar19 != 0) {
              iVar8 = thunk_FUN_1801db2d0(lVar19,0,0);
              uVar5 = DAT_181afb0d4;
              uVar17 = 0;
              while( true ) {
                if (((*(byte *)(DAT_1822ee950 + 0x12f) & 2) != 0) &&
                   (*(int *)(DAT_1822ee950 + 0xe0) == 0)) {
                  il2cpp_runtime_class_init();
                }
                lVar19 = *(longlong *)(*(longlong *)(DAT_1822ee950 + 0xb8) + 0x20);
                if (lVar19 == 0) break;
                if (*(int *)(lVar19 + 0x18) <= (int)uVar17) {
                  return 0;
                }
                if (((*(byte *)(DAT_1822ee950 + 0x12f) & 2) != 0) &&
                   (*(int *)(DAT_1822ee950 + 0xe0) == 0)) {
                  il2cpp_runtime_class_init();
                }
                lVar19 = *(longlong *)(*(longlong *)(DAT_1822ee950 + 0xb8) + 0x20);
                if (lVar19 == 0) break;
                lVar15 = (longlong)(int)uVar17;
                if (*(uint *)(lVar19 + 0x18) <= uVar17) {
                  uVar12 = thunk_FUN_1801f9600();
                  FUN_18023bce0(uVar12,0);
                  pcVar4 = (code *)swi(3);
                  uVar12 = (*pcVar4)();
                  return uVar12;
                }
                uVar12 = *(undefined8 *)(lVar19 + 0x20 + lVar15 * 0xc);
                uVar1 = *(undefined4 *)(lVar19 + 0x28 + lVar15 * 0xc);
                if (((*(byte *)(DAT_1822ab970 + 0x12f) & 2) != 0) &&
                   (*(int *)(DAT_1822ab970 + 0xe0) == 0)) {
                  il2cpp_runtime_class_init();
                }
                uStack_98 = uVar12;
                uStack_90 = uVar1;
                puVar11 = (undefined8 *)FUN_18154f940(auStack_68,&uStack_98,uVar5,0);
                uVar12 = *puVar11;
                uVar1 = *(undefined4 *)(puVar11 + 1);
                lVar19 = *(longlong *)(*(longlong *)(DAT_1822ee950 + 0xb8) + 0x20);
                if (lVar19 == 0) break;
                if (*(uint *)(lVar19 + 0x18) <= uVar17) {
                  uVar12 = thunk_FUN_1801f9600();
                  FUN_18023bce0(uVar12,0);
                  pcVar4 = (code *)swi(3);
                  uVar12 = (*pcVar4)();
                  return uVar12;
                }
                iVar16 = (int)*(float *)(lVar19 + 0x20 + lVar15 * 0xc) + *(int *)(param_2 + 0x40) +
                         param_4;
                if ((((-1 < iVar16) && (iVar16 < iVar8)) &&
                    (iVar14 = (int)*(float *)(lVar19 + 0x24 + lVar15 * 0xc) + param_5 +
                              *(int *)(param_2 + 0x44), -1 < iVar14)) &&
                   ((iVar14 < iVar7 && (0 < (int)(uVar13 & uVar18))))) {
                  if (((*(byte *)(DAT_1822ee950 + 0x12f) & 2) != 0) &&
                     (*(int *)(DAT_1822ee950 + 0xe0) == 0)) {
                    il2cpp_runtime_class_init();
                  }
                  lVar19 = *(longlong *)(*(longlong *)(DAT_1822ee950 + 0xb8) + 0x20);
                  if (lVar19 == 0) break;
                  if ((int)uVar17 < *(int *)(lVar19 + 0x18) + -2) {
                    if ((*(longlong *)(param_2 + 0x10) == 0) ||
                       (lVar19 = FUN_1800ddc20(*(longlong *)(param_2 + 0x10),param_3,DAT_1822a64a0),
                       lVar19 == 0)) break;
                    uVar9 = FUN_1800dcca0(lVar19,(longlong)iVar16,(longlong)iVar14);
                    uStack_88 = uVar12;
                    uStack_80 = uVar1;
                    uVar10 = FUN_180c577c0(&uStack_88,0);
                    if ((int)(uVar9 & uVar10) < 1) goto LAB_180c4f1b2;
                  }
                  if (((*(byte *)(DAT_1822ee950 + 0x12f) & 2) != 0) &&
                     (*(int *)(DAT_1822ee950 + 0xe0) == 0)) {
                    il2cpp_runtime_class_init();
                  }
                  lVar19 = *(longlong *)(*(longlong *)(DAT_1822ee950 + 0xb8) + 0x20);
                  if (lVar19 == 0) break;
                  if (*(uint *)(lVar19 + 0x18) <= uVar17) {
                    uVar12 = thunk_FUN_1801f9600();
                    FUN_18023bce0(uVar12,0);
                    pcVar4 = (code *)swi(3);
                    uVar12 = (*pcVar4)();
                    return uVar12;
                  }
                  uStack_70 = *(undefined4 *)(lVar19 + 0x28 + lVar15 * 0xc);
                  uStack_78 = *(undefined8 *)(lVar19 + 0x20 + lVar15 * 0xc);
                  cVar6 = MapRouteSearcher__UpdateRouteMapCellStep
                                    (param_1,param_2,param_3,param_4,param_5,&uStack_78,param_6,0);
                  if (cVar6 != '\0') {
                    return 1;
                  }
                }
LAB_180c4f1b2:
                uVar17 = uVar17 + 1;
                uVar18 = uVar18 * 2;
              }
            }
          }
        }
      }
    }
  }
  FUN_18023bd10();
  pcVar4 = (code *)swi(3);
  uVar12 = (*pcVar4)();
  return uVar12;
}



/********************************************************************/
/* MapRouteSearcher$$SearchAroundCellWithoutCollision
 * RVA: 0xC4F260
 * Address: 0x180C4F260
 *******************************************************************/


undefined8
MapRouteSearcher__SearchAroundCellWithoutCollision
          (undefined8 param_1,undefined8 param_2,undefined4 param_3,undefined4 param_4,
          undefined4 param_5,undefined4 param_6)

{
  longlong lVar1;
  code *pcVar2;
  char cVar3;
  undefined8 uVar4;
  uint uVar5;
  undefined8 local_38;
  undefined4 local_30;
  
  if (DAT_181ff1ac6 == '\0') {
    thunk_FUN_180203190(DAT_1817dfba8);
    DAT_181ff1ac6 = '\x01';
  }
  uVar5 = 0;
  while( true ) {
    if (((*(byte *)(DAT_1822ee950 + 0x12f) & 2) != 0) && (*(int *)(DAT_1822ee950 + 0xe0) == 0)) {
      il2cpp_runtime_class_init(DAT_1822ee950);
    }
    lVar1 = *(longlong *)(*(longlong *)(DAT_1822ee950 + 0xb8) + 0x20);
    if (lVar1 == 0) break;
    if (*(int *)(lVar1 + 0x18) <= (int)uVar5) {
      return 0;
    }
    if (((*(byte *)(DAT_1822ee950 + 0x12f) & 2) != 0) && (*(int *)(DAT_1822ee950 + 0xe0) == 0)) {
      il2cpp_runtime_class_init(DAT_1822ee950);
    }
    lVar1 = *(longlong *)(*(longlong *)(DAT_1822ee950 + 0xb8) + 0x20);
    if (lVar1 == 0) break;
    if (*(uint *)(lVar1 + 0x18) <= uVar5) {
      uVar4 = thunk_FUN_1801f9600();
      FUN_18023bce0(uVar4,0);
      pcVar2 = (code *)swi(3);
      uVar4 = (*pcVar2)();
      return uVar4;
    }
    local_30 = *(undefined4 *)(lVar1 + 0x28 + (longlong)(int)uVar5 * 0xc);
    local_38 = *(undefined8 *)(lVar1 + 0x20 + (longlong)(int)uVar5 * 0xc);
    cVar3 = MapRouteSearcher__UpdateRouteMapCellStep
                      (param_1,param_2,param_3,param_4,param_5,&local_38,param_6,0);
    if (cVar3 != '\0') {
      return 1;
    }
    uVar5 = uVar5 + 1;
  }
  FUN_18023bd10();
  pcVar2 = (code *)swi(3);
  uVar4 = (*pcVar2)();
  return uVar4;
}



/********************************************************************/
/* MapRouteSearcher$$SearchShortestRoute
 * RVA: 0xC4F3D0
 * Address: 0x180C4F3D0
 *******************************************************************/


undefined8
MapRouteSearcher__SearchShortestRoute
          (longlong *param_1,longlong param_2,longlong param_3,float *param_4,longlong param_5,
          int param_6)

{
  code *pcVar1;
  float fVar2;
  float fVar3;
  float fVar4;
  char cVar5;
  char cVar6;
  int iVar7;
  ulonglong uVar8;
  longlong lVar9;
  longlong lVar10;
  undefined8 uVar11;
  int iVar12;
  int iVar13;
  uint uVar14;
  int iVar15;
  int iVar16;
  float fVar17;
  undefined8 local_d8;
  float local_d0;
  int local_c8;
  undefined8 local_b8;
  float local_b0;
  int local_a8;
  int local_a4;
  int local_a0;
  int local_9c;
  int local_98;
  int local_94;
  int local_90;
  undefined8 local_88;
  float local_80;
  
  if (DAT_181ff1abf == '\0') {
    thunk_FUN_180203190(DAT_1817dfbac);
    DAT_181ff1abf = '\x01';
  }
  param_6 = param_6 + -1;
  if (param_5 == 0) goto LAB_180c50431;
  local_d0 = *(float *)(param_5 + 0x18);
  local_d8 = *(undefined8 *)(param_5 + 0x10);
  fVar17 = (float)local_d8;
  iVar12 = (int)fVar17;
  if (iVar12 == (int)*param_4) {
    local_b0 = *(float *)(param_5 + 0x18);
    uVar11 = *(undefined8 *)param_4;
    local_80 = param_4[2];
    local_b8._4_4_ = (float)((ulonglong)local_d8 >> 0x20);
    iVar7 = (int)local_b8._4_4_;
    local_88._4_4_ = (float)((ulonglong)uVar11 >> 0x20);
    iVar13 = (int)local_88._4_4_;
    local_b8 = local_d8;
    local_88 = uVar11;
    if (iVar7 != iVar13) goto LAB_180c4f571;
    local_80 = *(float *)(param_5 + 0x18);
    local_b0 = param_4[2];
    local_b8 = uVar11;
    if ((int)local_80 != (int)local_b0) goto LAB_180c4f571;
    do {
      if (*param_1 == 0) goto LAB_180c50431;
      local_b8 = *(undefined8 *)(param_5 + 0x10);
      local_b0 = *(float *)(param_5 + 0x18);
      FUN_1810e93e0(*param_1,&local_b8,DAT_1822ad428);
      param_5 = *(longlong *)(param_5 + 0x20);
    } while (param_5 != 0);
    if (*param_1 == 0) goto LAB_180c50431;
    FUN_1810ee7c0(*param_1,DAT_1822ad360);
LAB_180c4f52d:
    uVar11 = 1;
  }
  else {
LAB_180c4f571:
    if (((*(byte *)(DAT_1822ab970 + 0x12f) & 2) != 0) && (*(int *)(DAT_1822ab970 + 0xe0) == 0)) {
      il2cpp_runtime_class_init();
    }
    FUN_18154f6f0(&local_b8,0);
    fVar4 = local_d0;
    fVar2 = DAT_1818a4ce4;
    local_d0 = fVar4;
    if (param_3 == 0) goto LAB_180c50431;
    local_a8 = *(int *)(param_3 + 0x40);
    fVar3 = local_d8._4_4_;
    lVar10 = *(longlong *)(param_3 + 0x10);
    local_c8 = *(int *)(param_3 + 0x44);
    local_9c = *(int *)(param_3 + 0x18);
    local_a4 = *(int *)(param_3 + 0x1c);
    local_90 = *(int *)(param_3 + 0x20);
    cVar6 = *(char *)(param_3 + 0x48);
    if (0 < (int)local_d8._4_4_) {
      local_d8._4_4_ = local_d8._4_4_ - DAT_1818a4ce4;
      local_d8 = CONCAT44(local_d8._4_4_,fVar17);
      if (param_2 == 0) goto LAB_180c50431;
      iVar13 = (int)local_d8._4_4_;
      uVar14 = (uint)local_d0;
      iVar7 = FUN_180156650(param_2,(longlong)(int)uVar14,(longlong)iVar12,(longlong)iVar13);
      if (iVar7 == param_6) {
        if (cVar6 == '\0') {
LAB_180c4f6d0:
          lVar9 = thunk_FUN_180207de0(DAT_1822c8968);
          FUN_180c5bd00(lVar9,0);
          if (lVar9 == 0) goto LAB_180c50431;
          *(undefined8 *)(lVar9 + 0x10) = local_d8;
          *(float *)(lVar9 + 0x18) = local_d0;
          *(longlong *)(lVar9 + 0x20) = param_5;
          thunk_FUN_180239040((longlong *)(lVar9 + 0x20),param_5);
          local_b8 = *(undefined8 *)param_4;
          local_b0 = param_4[2];
          cVar5 = MapRouteSearcher__SearchShortestRoute
                            (param_1,param_2,param_3,&local_b8,lVar9,param_6,0);
          if (cVar5 != '\0') goto LAB_180c4f52d;
        }
        else {
          if (lVar10 == 0) goto LAB_180c50431;
          if (*(uint *)(lVar10 + 0x18) <= uVar14) {
            FUN_180d9d940(0);
          }
          lVar9 = *(longlong *)(*(longlong *)(lVar10 + 0x10) + 0x20 + (longlong)(int)uVar14 * 8);
          if (lVar9 == 0) goto LAB_180c50431;
          iVar7 = iVar12 + local_a8;
          uVar8 = FUN_1800dcca0(lVar9,(longlong)iVar7,(longlong)(local_c8 + iVar13));
          if ((uVar8 & 8) != 0) {
            lVar9 = FUN_1800ddc20(lVar10,uVar14,DAT_1822a64a0);
            if (lVar9 == 0) goto LAB_180c50431;
            uVar8 = FUN_1800dcca0(lVar9,(longlong)iVar7,(longlong)((int)fVar3 + local_c8));
            if ((uVar8 & 1) != 0) goto LAB_180c4f6d0;
          }
        }
      }
    }
    local_94 = iVar12 + 1;
    if (local_94 < local_9c) {
      local_d8 = CONCAT44(fVar3,fVar17 + fVar2);
      local_d0 = fVar4;
      if (param_2 == 0) goto LAB_180c50431;
      iVar13 = (int)(fVar17 + fVar2);
      uVar14 = (uint)fVar4;
      iVar7 = FUN_180156650(param_2,(longlong)(int)uVar14,(longlong)iVar13,(longlong)(int)fVar3);
      if (iVar7 == param_6) {
        if (cVar6 == '\0') {
LAB_180c4f847:
          lVar9 = thunk_FUN_180207de0(DAT_1822c8968);
          FUN_180c5bd00(lVar9,0);
          if (lVar9 == 0) goto LAB_180c50431;
          *(undefined8 *)(lVar9 + 0x10) = local_d8;
          *(float *)(lVar9 + 0x18) = local_d0;
          *(longlong *)(lVar9 + 0x20) = param_5;
          thunk_FUN_180239040((longlong *)(lVar9 + 0x20),param_5);
          local_b8 = *(undefined8 *)param_4;
          local_b0 = param_4[2];
          cVar5 = MapRouteSearcher__SearchShortestRoute
                            (param_1,param_2,param_3,&local_b8,lVar9,param_6,0);
          if (cVar5 != '\0') goto LAB_180c4f52d;
        }
        else {
          if (lVar10 == 0) goto LAB_180c50431;
          if (*(uint *)(lVar10 + 0x18) <= uVar14) {
            FUN_180d9d940(0);
          }
          lVar9 = *(longlong *)(*(longlong *)(lVar10 + 0x10) + 0x20 + (longlong)(int)uVar14 * 8);
          if (lVar9 == 0) goto LAB_180c50431;
          iVar7 = (int)fVar3 + local_c8;
          uVar8 = FUN_1800dcca0(lVar9,(longlong)(local_a8 + iVar13),(longlong)iVar7);
          if ((uVar8 & 2) != 0) {
            lVar9 = FUN_1800ddc20(lVar10,uVar14,DAT_1822a64a0);
            if (lVar9 == 0) goto LAB_180c50431;
            uVar8 = FUN_1800dcca0(lVar9,(longlong)(iVar12 + local_a8),(longlong)iVar7);
            if ((uVar8 & 4) != 0) goto LAB_180c4f847;
          }
        }
      }
    }
    local_a0 = (int)fVar3 + 1;
    if (local_a0 < local_a4) {
      local_d8 = CONCAT44(fVar3 + fVar2,fVar17);
      local_d0 = fVar4;
      if (param_2 == 0) goto LAB_180c50431;
      local_98 = (int)(fVar3 + fVar2);
      uVar14 = (uint)fVar4;
      iVar7 = FUN_180156650(param_2,(longlong)(int)uVar14,(longlong)iVar12,(longlong)local_98);
      if (iVar7 == param_6) {
        if (cVar6 == '\0') {
LAB_180c4f9c5:
          lVar9 = thunk_FUN_180207de0(DAT_1822c8968);
          FUN_180c5bd00(lVar9,0);
          if (lVar9 == 0) goto LAB_180c50431;
          *(undefined8 *)(lVar9 + 0x10) = local_d8;
          *(float *)(lVar9 + 0x18) = local_d0;
          *(longlong *)(lVar9 + 0x20) = param_5;
          thunk_FUN_180239040((longlong *)(lVar9 + 0x20),param_5);
          local_b8 = *(undefined8 *)param_4;
          local_b0 = param_4[2];
          cVar5 = MapRouteSearcher__SearchShortestRoute
                            (param_1,param_2,param_3,&local_b8,lVar9,param_6,0);
          if (cVar5 != '\0') goto LAB_180c4f52d;
        }
        else {
          if (lVar10 == 0) goto LAB_180c50431;
          if (*(uint *)(lVar10 + 0x18) <= uVar14) {
            FUN_180d9d940(0);
          }
          lVar9 = *(longlong *)(*(longlong *)(lVar10 + 0x10) + 0x20 + (longlong)(int)uVar14 * 8);
          if (lVar9 == 0) goto LAB_180c50431;
          iVar7 = iVar12 + local_a8;
          uVar8 = FUN_1800dcca0(lVar9,(longlong)iVar7,(longlong)(local_98 + local_c8));
          if ((uVar8 & 1) != 0) {
            lVar9 = FUN_1800ddc20(lVar10,uVar14,DAT_1822a64a0);
            if (lVar9 == 0) goto LAB_180c50431;
            uVar8 = FUN_1800dcca0(lVar9,(longlong)iVar7,(longlong)((int)fVar3 + local_c8));
            if ((uVar8 & 8) != 0) goto LAB_180c4f9c5;
          }
        }
      }
    }
    if (0 < iVar12) {
      local_d8 = CONCAT44(fVar3,fVar17 - fVar2);
      local_d0 = fVar4;
      if (param_2 == 0) goto LAB_180c50431;
      local_98 = (int)(fVar17 - fVar2);
      uVar14 = (uint)fVar4;
      iVar7 = FUN_180156650(param_2,(longlong)(int)uVar14,(longlong)local_98,(longlong)(int)fVar3);
      if (iVar7 == param_6) {
        if (cVar6 == '\0') {
LAB_180c4fb36:
          lVar9 = thunk_FUN_180207de0(DAT_1822c8968);
          FUN_180c5bd00(lVar9,0);
          if (lVar9 == 0) goto LAB_180c50431;
          *(undefined8 *)(lVar9 + 0x10) = local_d8;
          *(float *)(lVar9 + 0x18) = local_d0;
          *(longlong *)(lVar9 + 0x20) = param_5;
          thunk_FUN_180239040((longlong *)(lVar9 + 0x20),param_5);
          local_b8 = *(undefined8 *)param_4;
          local_b0 = param_4[2];
          cVar5 = MapRouteSearcher__SearchShortestRoute
                            (param_1,param_2,param_3,&local_b8,lVar9,param_6,0);
          if (cVar5 != '\0') goto LAB_180c4f52d;
        }
        else {
          if (lVar10 == 0) goto LAB_180c50431;
          if (*(uint *)(lVar10 + 0x18) <= uVar14) {
            FUN_180d9d940(0);
          }
          lVar9 = *(longlong *)(*(longlong *)(lVar10 + 0x10) + 0x20 + (longlong)(int)uVar14 * 8);
          if (lVar9 == 0) goto LAB_180c50431;
          iVar7 = (int)fVar3 + local_c8;
          uVar8 = FUN_1800dcca0(lVar9,(longlong)(local_98 + local_a8),(longlong)iVar7);
          if ((uVar8 & 4) != 0) {
            lVar9 = FUN_1800ddc20(lVar10,uVar14,DAT_1822a64a0);
            if (lVar9 == 0) goto LAB_180c50431;
            uVar8 = FUN_1800dcca0(lVar9,(longlong)(iVar12 + local_a8),(longlong)iVar7);
            if ((uVar8 & 2) != 0) goto LAB_180c4fb36;
          }
        }
      }
    }
    if (local_94 < local_9c) {
      if (0 < (int)fVar3) {
        local_d8 = CONCAT44(fVar3 - fVar2,fVar17 + fVar2);
        local_d0 = fVar4;
        if (param_2 == 0) goto LAB_180c50431;
        iVar16 = (int)(fVar3 - fVar2);
        iVar13 = (int)(fVar17 + fVar2);
        iVar15 = (int)fVar4;
        iVar7 = FUN_180156650(param_2,(longlong)iVar15,(longlong)iVar13,(longlong)iVar16);
        if (iVar7 == param_6) {
          if (cVar6 == '\0') {
LAB_180c4fcda:
            lVar9 = thunk_FUN_180207de0(DAT_1822c8968);
            FUN_180c5bd00(lVar9,0);
            if (lVar9 == 0) goto LAB_180c50431;
            *(undefined8 *)(lVar9 + 0x10) = local_d8;
            *(float *)(lVar9 + 0x18) = local_d0;
            *(longlong *)(lVar9 + 0x20) = param_5;
            thunk_FUN_180239040((longlong *)(lVar9 + 0x20),param_5);
            local_b8 = *(undefined8 *)param_4;
            local_b0 = param_4[2];
            cVar5 = MapRouteSearcher__SearchShortestRoute
                              (param_1,param_2,param_3,&local_b8,lVar9,param_6,0);
            if (cVar5 != '\0') goto LAB_180c4f52d;
            if (local_9c <= local_94) goto LAB_180c4ff02;
          }
          else {
            if ((lVar10 == 0) ||
               (lVar9 = FUN_1800ddc20(lVar10,iVar15,DAT_1822a64a0), iVar7 = local_a8, lVar9 == 0))
            goto LAB_180c50431;
            uVar8 = FUN_1800dcca0(lVar9,(longlong)(iVar13 + local_a8),(longlong)(local_c8 + iVar16))
            ;
            if ((uVar8 & 0x40) != 0) {
              lVar9 = FUN_1800ddc20(lVar10,iVar15,DAT_1822a64a0);
              if (lVar9 == 0) goto LAB_180c50431;
              uVar8 = FUN_1800dcca0(lVar9,(longlong)(iVar12 + iVar7),
                                    (longlong)((int)fVar3 + local_c8));
              if ((uVar8 & 0x20) != 0) goto LAB_180c4fcda;
            }
          }
        }
      }
      if (local_a0 < local_a4) {
        local_d8 = CONCAT44(fVar3 + fVar2,fVar17 + fVar2);
        local_d0 = fVar4;
        if (param_2 == 0) goto LAB_180c50431;
        iVar16 = (int)(fVar3 + fVar2);
        iVar13 = (int)(fVar17 + fVar2);
        iVar15 = (int)fVar4;
        iVar7 = FUN_180156650(param_2,(longlong)iVar15,(longlong)iVar13,(longlong)iVar16);
        if (iVar7 == param_6) {
          if (cVar6 == '\0') {
LAB_180c4fe6e:
            lVar9 = thunk_FUN_180207de0(DAT_1822c8968);
            FUN_180c5bd00(lVar9,0);
            if (lVar9 == 0) goto LAB_180c50431;
            *(undefined8 *)(lVar9 + 0x10) = local_d8;
            *(float *)(lVar9 + 0x18) = local_d0;
            *(longlong *)(lVar9 + 0x20) = param_5;
            thunk_FUN_180239040((longlong *)(lVar9 + 0x20),param_5);
            local_b8 = *(undefined8 *)param_4;
            local_b0 = param_4[2];
            cVar5 = MapRouteSearcher__SearchShortestRoute
                              (param_1,param_2,param_3,&local_b8,lVar9,param_6,0);
            if (cVar5 != '\0') goto LAB_180c4f52d;
          }
          else {
            if ((lVar10 == 0) ||
               (lVar9 = FUN_1800ddc20(lVar10,iVar15,DAT_1822a64a0), iVar7 = local_a8, lVar9 == 0))
            goto LAB_180c50431;
            uVar8 = FUN_1800dcca0(lVar9,(longlong)(iVar13 + local_a8),(longlong)(local_c8 + iVar16))
            ;
            if ((uVar8 & 0x10) != 0) {
              lVar9 = FUN_1800ddc20(lVar10,iVar15,DAT_1822a64a0);
              if (lVar9 == 0) goto LAB_180c50431;
              uVar8 = FUN_1800dcca0(lVar9,(longlong)(iVar12 + iVar7),
                                    (longlong)((int)fVar3 + local_c8));
              if ((uVar8 & 0x80) != 0) goto LAB_180c4fe6e;
            }
          }
        }
      }
    }
LAB_180c4ff02:
    if (0 < iVar12) {
      if (local_a0 < local_a4) {
        local_d8 = CONCAT44(fVar3 + fVar2,fVar17 - fVar2);
        local_d0 = fVar4;
        if (param_2 == 0) goto LAB_180c50431;
        iVar16 = (int)(fVar3 + fVar2);
        iVar13 = (int)(fVar17 - fVar2);
        iVar15 = (int)fVar4;
        iVar7 = FUN_180156650(param_2,(longlong)iVar15,(longlong)iVar13,(longlong)iVar16);
        if (iVar7 == param_6) {
          if (cVar6 == '\0') {
LAB_180c4fffc:
            lVar9 = thunk_FUN_180207de0(DAT_1822c8968);
            FUN_180c5bd00(lVar9,0);
            if (lVar9 == 0) goto LAB_180c50431;
            *(undefined8 *)(lVar9 + 0x10) = local_d8;
            *(float *)(lVar9 + 0x18) = local_d0;
            *(longlong *)(lVar9 + 0x20) = param_5;
            thunk_FUN_180239040((longlong *)(lVar9 + 0x20),param_5);
            local_b8 = *(undefined8 *)param_4;
            local_b0 = param_4[2];
            cVar5 = MapRouteSearcher__SearchShortestRoute
                              (param_1,param_2,param_3,&local_b8,lVar9,param_6,0);
            if (cVar5 != '\0') goto LAB_180c4f52d;
            if (iVar12 < 1) goto LAB_180c50222;
          }
          else {
            if ((lVar10 == 0) ||
               (lVar9 = FUN_1800ddc20(lVar10,iVar15,DAT_1822a64a0), iVar7 = local_a8, lVar9 == 0))
            goto LAB_180c50431;
            uVar8 = FUN_1800dcca0(lVar9,(longlong)(iVar13 + local_a8),(longlong)(local_c8 + iVar16))
            ;
            if ((uVar8 & 0x20) != 0) {
              lVar9 = FUN_1800ddc20(lVar10,iVar15,DAT_1822a64a0);
              if (lVar9 == 0) goto LAB_180c50431;
              uVar8 = FUN_1800dcca0(lVar9,(longlong)(iVar12 + iVar7),
                                    (longlong)((int)fVar3 + local_c8));
              if ((uVar8 & 0x40) != 0) goto LAB_180c4fffc;
            }
          }
        }
      }
      if (0 < (int)fVar3) {
        local_d8 = CONCAT44(fVar3 - fVar2,fVar17 - fVar2);
        local_d0 = fVar4;
        if (param_2 == 0) goto LAB_180c50431;
        iVar16 = (int)(fVar3 - fVar2);
        iVar13 = (int)(fVar17 - fVar2);
        iVar15 = (int)fVar4;
        iVar7 = FUN_180156650(param_2,(longlong)iVar15,(longlong)iVar13,(longlong)iVar16);
        if (iVar7 == param_6) {
          if (cVar6 == '\0') {
LAB_180c5018e:
            lVar10 = thunk_FUN_180207de0(DAT_1822c8968);
            FUN_180c5bd00(lVar10,0);
            if (lVar10 == 0) goto LAB_180c50431;
            *(undefined8 *)(lVar10 + 0x10) = local_d8;
            *(float *)(lVar10 + 0x18) = local_d0;
            *(longlong *)(lVar10 + 0x20) = param_5;
            thunk_FUN_180239040((longlong *)(lVar10 + 0x20),param_5);
            local_b8 = *(undefined8 *)param_4;
            local_b0 = param_4[2];
            cVar6 = MapRouteSearcher__SearchShortestRoute
                              (param_1,param_2,param_3,&local_b8,lVar10,param_6,0);
            if (cVar6 != '\0') goto LAB_180c4f52d;
          }
          else {
            if ((lVar10 == 0) ||
               (lVar9 = FUN_1800ddc20(lVar10,iVar15,DAT_1822a64a0), iVar7 = local_a8, lVar9 == 0))
            goto LAB_180c50431;
            uVar8 = FUN_1800dcca0(lVar9,(longlong)(iVar13 + local_a8),(longlong)(local_c8 + iVar16))
            ;
            if ((uVar8 & 0x80) != 0) {
              lVar10 = FUN_1800ddc20(lVar10,iVar15,DAT_1822a64a0);
              if (lVar10 == 0) goto LAB_180c50431;
              uVar8 = FUN_1800dcca0(lVar10,(longlong)(iVar12 + iVar7),
                                    (longlong)((int)fVar3 + local_c8));
              if ((uVar8 & 0x10) != 0) goto LAB_180c5018e;
            }
          }
        }
      }
    }
LAB_180c50222:
    iVar7 = (int)fVar4;
    if (iVar7 + 1 < local_90) {
      if (param_2 == 0) goto LAB_180c50431;
      iVar13 = FUN_180156650(param_2,(longlong)(iVar7 + 1),(longlong)iVar12,(longlong)(int)fVar3);
      if (iVar13 == param_6) {
        lVar10 = thunk_FUN_180207de0(DAT_1822c8968);
        FUN_180c5bd00(lVar10,0);
        local_d8 = 0;
        local_d0 = 0.0;
        FUN_18154f0a0(&local_d8,fVar17,fVar3,fVar4 + fVar2,0);
        if (lVar10 == 0) {
          FUN_18023bd10();
          pcVar1 = (code *)swi(3);
          uVar11 = (*pcVar1)();
          return uVar11;
        }
        *(undefined8 *)(lVar10 + 0x10) = local_d8;
        *(float *)(lVar10 + 0x18) = local_d0;
        *(longlong *)(lVar10 + 0x20) = param_5;
        thunk_FUN_180239040((longlong *)(lVar10 + 0x20),param_5);
        local_b8 = *(undefined8 *)param_4;
        local_b0 = param_4[2];
        cVar6 = MapRouteSearcher__SearchShortestRoute
                          (param_1,param_2,param_3,&local_b8,lVar10,param_6,0);
        if (cVar6 != '\0') goto LAB_180c4f52d;
      }
    }
    if (0 < iVar7) {
      if (param_2 == 0) {
LAB_180c50431:
        FUN_18023bd10();
        pcVar1 = (code *)swi(3);
        uVar11 = (*pcVar1)();
        return uVar11;
      }
      iVar12 = FUN_180156650(param_2,(longlong)(iVar7 + -1),(longlong)iVar12,(longlong)(int)fVar3);
      if (iVar12 == param_6) {
        lVar10 = thunk_FUN_180207de0(DAT_1822c8968);
        FUN_180c5bd00(lVar10,0);
        local_d8 = 0;
        local_d0 = 0.0;
        FUN_18154f0a0(&local_d8,fVar17,fVar3,fVar4 - fVar2,0);
        if (lVar10 == 0) {
          FUN_18023bd10();
          pcVar1 = (code *)swi(3);
          uVar11 = (*pcVar1)();
          return uVar11;
        }
        *(undefined8 *)(lVar10 + 0x10) = local_d8;
        *(float *)(lVar10 + 0x18) = local_d0;
        *(longlong *)(lVar10 + 0x20) = param_5;
        thunk_FUN_180239040((longlong *)(lVar10 + 0x20),param_5);
        local_b8 = *(undefined8 *)param_4;
        local_b0 = param_4[2];
        cVar6 = MapRouteSearcher__SearchShortestRoute
                          (param_1,param_2,param_3,&local_b8,lVar10,param_6,0);
        if (cVar6 != '\0') goto LAB_180c4f52d;
      }
    }
    uVar11 = 0;
  }
  return uVar11;
}



/********************************************************************/
/* MapRouteSearcher$$SearchSimple
 * RVA: 0xC50450
 * Address: 0x180C50450
 *******************************************************************/


longlong MapRouteSearcher__SearchSimple(longlong *param_1,float *param_2,float *param_3)

{
  float fVar1;
  undefined8 uVar2;
  undefined8 uVar3;
  longlong lVar4;
  code *pcVar5;
  uint uVar6;
  undefined8 uVar7;
  char cVar8;
  longlong lVar9;
  undefined8 *puVar10;
  ushort uVar11;
  int iVar12;
  int iVar13;
  int iVar14;
  float fVar15;
  float fVar16;
  float fVar17;
  float fVar18;
  float fVar19;
  float fVar20;
  float fVar21;
  undefined8 local_118;
  float local_110;
  undefined8 local_108;
  float local_100;
  undefined8 local_f8;
  float local_f0;
  undefined8 local_e8;
  undefined8 uStack_e0;
  undefined8 local_d8;
  undefined8 uStack_d0;
  
  if (DAT_181ff1ac0 == '\0') {
    thunk_FUN_180203190(DAT_1817dfbc4);
    DAT_181ff1ac0 = '\x01';
  }
  lVar9 = thunk_FUN_180207de0(DAT_1822a72d0);
  FUN_1810f2350(lVar9,DAT_1822ad4a0);
  if (((*(byte *)(DAT_1822ab970 + 0x12f) & 2) != 0) && (*(int *)(DAT_1822ab970 + 0xe0) == 0)) {
    il2cpp_runtime_class_init();
  }
  local_118 = *(undefined8 *)param_3;
  local_110 = param_3[2];
  local_108 = *(undefined8 *)param_2;
  local_100 = param_2[2];
  cVar8 = FUN_18154f810(&local_108,&local_118,0);
  if (cVar8 == '\0') {
    if (param_1 == (longlong *)0x0) {
LAB_180c510ae:
      FUN_18023bd10();
      pcVar5 = (code *)swi(3);
      lVar9 = (*pcVar5)();
      return lVar9;
    }
    lVar4 = *param_1;
    uVar11 = 0;
    if (*(ushort *)(lVar4 + 0x126) != 0) {
      do {
        if (*(longlong *)(*(longlong *)(lVar4 + 0xb0) + (ulonglong)uVar11 * 0x10) == DAT_1822fc9e0)
        {
          puVar10 = (undefined8 *)
                    (((ulonglong)
                      (*(int *)(*(longlong *)(lVar4 + 0xb0) + 8 + (ulonglong)uVar11 * 0x10) + 0x11)
                     + 0x13) * 0x10 + lVar4);
          goto LAB_180c505cc;
        }
        uVar11 = uVar11 + 1;
      } while (uVar11 < *(ushort *)(lVar4 + 0x126));
    }
    puVar10 = (undefined8 *)FUN_1801f9690(param_1,DAT_1822fc9e0,0x11);
LAB_180c505cc:
    puVar10 = (undefined8 *)(*(code *)*puVar10)(&local_e8,param_1,puVar10[1]);
    local_d8 = *puVar10;
    uStack_d0 = puVar10[1];
    fVar15 = (float)FUN_181062850(&local_d8,0);
    FUN_180ab8ea0(&local_d8,fVar15 * DAT_181afb090,0);
    fVar15 = (float)FUN_1810627a0(&local_d8,0);
    FUN_180b77090(&local_d8,fVar15 * DAT_181afb090,0);
    FUN_1805c4f50(&local_d8,0,0);
    FUN_1805c4f40(&local_d8,0,0);
    fVar15 = *param_3;
    fVar1 = *param_2;
    if (((*(byte *)(DAT_1822ab7c8 + 0x12f) & 2) != 0) && (*(int *)(DAT_1822ab7c8 + 0xe0) == 0)) {
      il2cpp_runtime_class_init();
    }
    fVar16 = (float)FUN_18104eca0();
    uVar6 = DAT_181afb0e0;
    local_e8 = local_d8;
    uStack_e0 = uStack_d0;
    fVar21 = (float)((uint)(fVar15 - fVar1) & DAT_181afb0e0);
    fVar17 = (float)FUN_181062850(&local_d8,0);
    fVar17 = fVar15 - fVar17;
    if (DAT_181ff1aea == '\0') {
      thunk_FUN_180203190(DAT_1817e0508);
      DAT_181ff1aea = '\x01';
    }
    fVar18 = (float)FUN_181062850(&local_e8,0);
    if ((0.0 < fVar18) &&
       ((fVar19 = (float)FUN_180aa9ad0(&local_e8,0), fVar17 < fVar19 || (fVar19 + fVar18 <= fVar17))
       )) {
      if (((*(byte *)(DAT_1822ab7c8 + 0x12f) & 2) != 0) && (*(int *)(DAT_1822ab7c8 + 0xe0) == 0)) {
        il2cpp_runtime_class_init();
      }
      fVar19 = (float)FUN_18104eca0();
      fVar17 = fVar17 - fVar19 * fVar18;
    }
    fVar17 = (float)((uint)(fVar17 - fVar1) & uVar6);
    if (fVar17 < fVar21) {
      local_e8 = local_d8;
      uStack_e0 = uStack_d0;
      fVar21 = (float)FUN_181062850(&local_d8,0);
      if (DAT_181ff1aea == '\0') {
        thunk_FUN_180203190(DAT_1817e0508);
        DAT_181ff1aea = '\x01';
      }
      fVar16 = (float)FUN_181062850(&local_e8,0);
      if ((0.0 < fVar16) &&
         ((fVar18 = (float)FUN_180aa9ad0(&local_e8,0), fVar15 - fVar21 < fVar18 ||
          (fVar18 + fVar16 <= fVar15 - fVar21)))) {
        if (((*(byte *)(DAT_1822ab7c8 + 0x12f) & 2) != 0) && (*(int *)(DAT_1822ab7c8 + 0xe0) == 0))
        {
          il2cpp_runtime_class_init();
        }
        FUN_18104eca0();
      }
      if (((*(byte *)(DAT_1822ab7c8 + 0x12f) & 2) != 0) && (*(int *)(DAT_1822ab7c8 + 0xe0) == 0)) {
        il2cpp_runtime_class_init();
      }
      fVar16 = (float)FUN_18104eca0();
      fVar21 = fVar17;
    }
    local_e8 = local_d8;
    uStack_e0 = uStack_d0;
    fVar17 = (float)FUN_181062850(&local_d8,0);
    fVar17 = fVar17 + fVar15;
    if (DAT_181ff1aea == '\0') {
      thunk_FUN_180203190(DAT_1817e0508);
      DAT_181ff1aea = '\x01';
    }
    fVar18 = (float)FUN_181062850(&local_e8,0);
    if ((0.0 < fVar18) &&
       ((fVar19 = (float)FUN_180aa9ad0(&local_e8,0), fVar17 < fVar19 || (fVar19 + fVar18 <= fVar17))
       )) {
      if (((*(byte *)(DAT_1822ab7c8 + 0x12f) & 2) != 0) && (*(int *)(DAT_1822ab7c8 + 0xe0) == 0)) {
        il2cpp_runtime_class_init();
      }
      fVar19 = (float)FUN_18104eca0();
      fVar17 = fVar17 - fVar19 * fVar18;
    }
    if (((*(byte *)(DAT_1822ab7c8 + 0x12f) & 2) != 0) && (*(int *)(DAT_1822ab7c8 + 0xe0) == 0)) {
      il2cpp_runtime_class_init();
    }
    fVar17 = (float)((uint)(fVar17 - fVar1) & uVar6);
    if (fVar17 < fVar21) {
      local_e8 = local_d8;
      uStack_e0 = uStack_d0;
      fVar21 = (float)FUN_181062850(&local_d8,0);
      if (DAT_181ff1aea == '\0') {
        thunk_FUN_180203190(DAT_1817e0508);
        DAT_181ff1aea = '\x01';
      }
      fVar16 = (float)FUN_181062850(&local_e8,0);
      if ((0.0 < fVar16) &&
         ((fVar18 = (float)FUN_180aa9ad0(&local_e8,0), fVar21 + fVar15 < fVar18 ||
          (fVar18 + fVar16 <= fVar21 + fVar15)))) {
        if (((*(byte *)(DAT_1822ab7c8 + 0x12f) & 2) != 0) && (*(int *)(DAT_1822ab7c8 + 0xe0) == 0))
        {
          il2cpp_runtime_class_init();
        }
        FUN_18104eca0();
      }
      if (((*(byte *)(DAT_1822ab7c8 + 0x12f) & 2) != 0) && (*(int *)(DAT_1822ab7c8 + 0xe0) == 0)) {
        il2cpp_runtime_class_init();
      }
      fVar16 = (float)FUN_18104eca0();
      fVar21 = fVar17;
    }
    local_108 = *(undefined8 *)param_3;
    local_100 = param_3[2];
    local_118 = *(undefined8 *)param_2;
    local_110 = param_2[2];
    if (((*(byte *)(DAT_1822ab7c8 + 0x12f) & 2) != 0) && (*(int *)(DAT_1822ab7c8 + 0xe0) == 0)) {
      il2cpp_runtime_class_init();
    }
    fVar18 = (float)FUN_18104eca0(local_108._4_4_ - local_118._4_4_,0);
    local_f8 = *(undefined8 *)param_2;
    uVar2 = *(undefined8 *)param_3;
    local_f0 = param_3[2];
    local_e8 = local_d8;
    uStack_e0 = uStack_d0;
    fVar15 = (float)((uint)((float)((ulonglong)*(undefined8 *)param_3 >> 0x20) -
                           (float)((ulonglong)local_f8 >> 0x20)) & uVar6);
    fVar17 = (float)FUN_1810627a0(&local_d8,0);
    fVar17 = (float)((ulonglong)uVar2 >> 0x20) - fVar17;
    local_f8 = uVar2;
    if (DAT_181ff1aeb == '\0') {
      thunk_FUN_180203190(DAT_1817e04e4);
      DAT_181ff1aeb = '\x01';
    }
    fVar19 = (float)FUN_1810627a0(&local_e8,0);
    if ((0.0 < fVar19) &&
       ((fVar20 = (float)FUN_181062880(&local_e8,0), fVar17 < fVar20 - fVar19 || (fVar20 <= fVar17))
       )) {
      if (((*(byte *)(DAT_1822ab7c8 + 0x12f) & 2) != 0) && (*(int *)(DAT_1822ab7c8 + 0xe0) == 0)) {
        il2cpp_runtime_class_init();
      }
      fVar20 = (float)FUN_18104eca0();
      fVar17 = fVar17 - fVar20 * fVar19;
    }
    local_f8 = *(undefined8 *)param_2;
    fVar17 = (float)((uint)(fVar17 - (float)((ulonglong)local_f8 >> 0x20)) & uVar6);
    if (fVar17 < fVar15) {
      local_f0 = param_3[2];
      uVar2 = *(undefined8 *)param_3;
      local_e8 = local_d8;
      uStack_e0 = uStack_d0;
      fVar15 = (float)FUN_1810627a0(&local_d8,0);
      fVar15 = (float)((ulonglong)uVar2 >> 0x20) - fVar15;
      local_f8 = uVar2;
      if (DAT_181ff1aeb == '\0') {
        thunk_FUN_180203190(DAT_1817e04e4);
        DAT_181ff1aeb = '\x01';
      }
      fVar18 = (float)FUN_1810627a0(&local_e8,0);
      if ((0.0 < fVar18) &&
         ((fVar19 = (float)FUN_181062880(&local_e8,0), fVar15 < fVar19 - fVar18 ||
          (fVar19 <= fVar15)))) {
        if (((*(byte *)(DAT_1822ab7c8 + 0x12f) & 2) != 0) && (*(int *)(DAT_1822ab7c8 + 0xe0) == 0))
        {
          il2cpp_runtime_class_init();
        }
        FUN_18104eca0();
      }
      local_108 = *(undefined8 *)param_2;
      local_100 = param_2[2];
      if (((*(byte *)(DAT_1822ab7c8 + 0x12f) & 2) != 0) && (*(int *)(DAT_1822ab7c8 + 0xe0) == 0)) {
        il2cpp_runtime_class_init();
      }
      fVar18 = (float)FUN_18104eca0();
      fVar15 = fVar17;
    }
    local_f0 = param_3[2];
    uVar2 = *(undefined8 *)param_3;
    local_e8 = local_d8;
    uStack_e0 = uStack_d0;
    fVar17 = (float)FUN_1810627a0(&local_d8,0);
    fVar17 = fVar17 + (float)((ulonglong)uVar2 >> 0x20);
    local_f8 = uVar2;
    if (DAT_181ff1aeb == '\0') {
      thunk_FUN_180203190(DAT_1817e04e4);
      DAT_181ff1aeb = '\x01';
    }
    fVar19 = (float)FUN_1810627a0(&local_e8,0);
    if ((0.0 < fVar19) &&
       ((fVar20 = (float)FUN_181062880(&local_e8,0), fVar17 < fVar20 - fVar19 || (fVar20 <= fVar17))
       )) {
      if (((*(byte *)(DAT_1822ab7c8 + 0x12f) & 2) != 0) && (*(int *)(DAT_1822ab7c8 + 0xe0) == 0)) {
        il2cpp_runtime_class_init();
      }
      fVar20 = (float)FUN_18104eca0();
      fVar17 = fVar17 - fVar20 * fVar19;
    }
    local_108 = *(undefined8 *)param_2;
    local_100 = param_2[2];
    if (((*(byte *)(DAT_1822ab7c8 + 0x12f) & 2) != 0) && (*(int *)(DAT_1822ab7c8 + 0xe0) == 0)) {
      il2cpp_runtime_class_init();
    }
    uVar7 = uStack_d0;
    uVar2 = local_d8;
    fVar17 = (float)((uint)(fVar17 - local_108._4_4_) & uVar6);
    if (fVar17 < fVar15) {
      local_f0 = param_3[2];
      uVar3 = *(undefined8 *)param_3;
      fVar15 = (float)FUN_1810627a0(&local_d8,0);
      local_e8 = uVar2;
      uStack_e0 = uVar7;
      local_f8 = uVar3;
      FUN_180c56a90(&local_e8,(float)((ulonglong)uVar3 >> 0x20) + fVar15,0);
      local_108 = *(undefined8 *)param_2;
      local_100 = param_2[2];
      if (((*(byte *)(DAT_1822ab7c8 + 0x12f) & 2) != 0) && (*(int *)(DAT_1822ab7c8 + 0xe0) == 0)) {
        il2cpp_runtime_class_init();
      }
      fVar18 = (float)FUN_18104eca0();
      fVar15 = fVar17;
    }
    fVar17 = DAT_1818a4ce4;
    local_100 = param_2[2];
    local_118 = *(undefined8 *)param_2;
    iVar12 = (int)local_100;
    if (iVar12 == 0) {
      iVar12 = 0x15d;
    }
    else if (iVar12 == 1) {
      iVar12 = 0xf9;
    }
    else if (iVar12 == 2) {
      iVar12 = 0x95;
    }
    else if (iVar12 == 3) {
      iVar12 = 0x31;
    }
    else {
      iVar12 = 0;
    }
    iVar14 = 1;
    iVar13 = 1;
    fVar20 = (float)iVar12;
    local_108 = local_118;
    local_110 = fVar20;
    fVar19 = DAT_1818a4ce4;
    while (fVar19 <= fVar21) {
      lVar4 = *param_1;
      uVar11 = 0;
      local_118._4_4_ = (float)((ulonglong)local_118 >> 0x20);
      local_118 = CONCAT44(local_118._4_4_,fVar19 * fVar16 + fVar1);
      if (*(ushort *)(lVar4 + 0x126) != 0) {
        do {
          if (*(longlong *)(*(longlong *)(lVar4 + 0xb0) + (ulonglong)uVar11 * 0x10) == DAT_1822fc9e0
             ) {
            puVar10 = (undefined8 *)
                      (((ulonglong)
                        (*(int *)(*(longlong *)(lVar4 + 0xb0) + 8 + (ulonglong)uVar11 * 0x10) + 3) +
                       0x13) * 0x10 + lVar4);
            goto LAB_180c50ec0;
          }
          uVar11 = uVar11 + 1;
        } while (uVar11 < *(ushort *)(lVar4 + 0x126));
      }
      puVar10 = (undefined8 *)FUN_1801f9690(param_1,DAT_1822fc9e0,3);
LAB_180c50ec0:
      local_108 = local_118;
      local_100 = fVar20;
      puVar10 = (undefined8 *)(*(code *)*puVar10)(&local_e8,param_1,&local_108,puVar10[1]);
      if (lVar9 == 0) goto LAB_180c510ae;
      local_f8 = *puVar10;
      local_f0 = *(float *)(puVar10 + 1);
      FUN_1810e93e0(lVar9,&local_f8,DAT_1822ad428);
      iVar13 = iVar13 + 1;
      fVar19 = (float)iVar13;
    }
    if (fVar17 <= fVar15) {
      local_f0 = param_2[2];
      local_f8._4_4_ = (float)((ulonglong)*(undefined8 *)param_2 >> 0x20);
      fVar1 = local_f8._4_4_;
      local_f8 = *(undefined8 *)param_2;
      do {
        lVar4 = *param_1;
        uVar11 = 0;
        local_118 = CONCAT44(fVar17 * fVar18 + fVar1,(undefined4)local_118);
        if (*(ushort *)(lVar4 + 0x126) != 0) {
          do {
            if (*(longlong *)(*(longlong *)(lVar4 + 0xb0) + (ulonglong)uVar11 * 0x10) ==
                DAT_1822fc9e0) {
              puVar10 = (undefined8 *)
                        (((ulonglong)
                          (*(int *)(*(longlong *)(lVar4 + 0xb0) + 8 + (ulonglong)uVar11 * 0x10) + 3)
                         + 0x13) * 0x10 + lVar4);
              goto LAB_180c50fae;
            }
            uVar11 = uVar11 + 1;
          } while (uVar11 < *(ushort *)(lVar4 + 0x126));
        }
        puVar10 = (undefined8 *)FUN_1801f9690(param_1,DAT_1822fc9e0,3);
LAB_180c50fae:
        local_f8 = local_118;
        local_f0 = fVar20;
        puVar10 = (undefined8 *)(*(code *)*puVar10)(&local_e8,param_1,&local_f8,puVar10[1]);
        if (lVar9 == 0) goto LAB_180c510ae;
        local_108 = *puVar10;
        local_100 = *(float *)(puVar10 + 1);
        FUN_1810e93e0(lVar9,&local_108,DAT_1822ad428);
        iVar14 = iVar14 + 1;
        fVar17 = (float)iVar14;
      } while (fVar17 <= fVar15);
    }
  }
  return lVar9;
}



/********************************************************************/
/* MapRouteSearcher$$SearchSpriteEntityDirection
 * RVA: 0xC510C0
 * Address: 0x180C510C0
 *******************************************************************/


void MapRouteSearcher__SearchSpriteEntityDirection
               (undefined8 param_1,undefined8 param_2,undefined8 *param_3)

{
  undefined8 uVar1;
  undefined4 uVar2;
  undefined8 *puVar3;
  undefined8 local_68;
  undefined4 local_60;
  undefined8 local_58;
  undefined4 local_50;
  undefined4 local_40;
  undefined local_38 [48];
  
  if (DAT_181ff1ac1 == '\0') {
    thunk_FUN_180203190(DAT_1817dfbe4);
    DAT_181ff1ac1 = '\x01';
  }
  puVar3 = (undefined8 *)
           MapRouteSearcher__EntityWorldPositionToCellPosition(&local_58,param_1,param_2,0);
  uVar2 = *(undefined4 *)(puVar3 + 1);
  uVar1 = *puVar3;
  local_40 = uVar2;
  if (((*(byte *)(DAT_1822ab970 + 0x12f) & 2) != 0) && (*(int *)(DAT_1822ab970 + 0xe0) == 0)) {
    il2cpp_runtime_class_init();
  }
  local_68 = *param_3;
  local_60 = *(undefined4 *)(param_3 + 1);
  local_58 = uVar1;
  local_50 = uVar2;
  puVar3 = (undefined8 *)FUN_18154f770(local_38,&local_58,&local_68,0);
  local_68 = *puVar3;
  local_60 = local_40;
  local_58 = uVar1;
  local_50 = uVar2;
  MapRouteSearcher__Search(param_1,&local_58,&local_68,0,0);
  return;
}



/********************************************************************/
/* MapRouteSearcher$$SearchSpriteEntityToCellPosition
 * RVA: 0xC511E0
 * Address: 0x180C511E0
 *******************************************************************/


void MapRouteSearcher__SearchSpriteEntityToCellPosition
               (undefined8 param_1,undefined8 param_2,undefined8 *param_3)

{
  undefined8 *puVar1;
  undefined8 local_38;
  undefined4 local_30;
  undefined8 local_28;
  undefined4 local_20;
  undefined local_18 [16];
  
  puVar1 = (undefined8 *)
           MapRouteSearcher__EntityWorldPositionToCellPosition(local_18,param_1,param_2,0);
  local_20 = *(undefined4 *)(puVar1 + 1);
  *(undefined4 *)(param_3 + 1) = local_20;
  local_30 = *(undefined4 *)(param_3 + 1);
  local_38 = *param_3;
  local_28 = *puVar1;
  MapRouteSearcher__Search(param_1,&local_28,&local_38,0,0);
  return;
}



/********************************************************************/
/* MapRouteSearcher$$Search
 * RVA: 0xC51270
 * Address: 0x180C51270
 *******************************************************************/


longlong MapRouteSearcher__Search(longlong *param_1,float *param_2,float *param_3,char param_4)

{
  float fVar1;
  longlong lVar2;
  code *pcVar3;
  bool bVar4;
  bool bVar5;
  longlong lVar6;
  char cVar7;
  undefined4 uVar8;
  int iVar9;
  int iVar10;
  int iVar11;
  int iVar12;
  longlong lVar13;
  undefined8 *puVar14;
  longlong lVar15;
  longlong lVar16;
  longlong *plVar17;
  undefined8 uVar18;
  ushort uVar19;
  int iVar20;
  ulonglong uVar21;
  ulonglong uVar22;
  int iVar23;
  uint uVar24;
  ulonglong uVar25;
  float fVar26;
  undefined8 uVar27;
  float fVar28;
  float fVar29;
  undefined4 uVar30;
  undefined8 local_168;
  float local_160;
  undefined8 local_158;
  float local_150;
  undefined8 local_148;
  float local_140;
  int local_138;
  undefined8 local_128;
  float local_120;
  int local_118;
  int local_114;
  longlong local_110;
  undefined8 local_108;
  float local_100;
  longlong local_f8;
  float local_f0;
  undefined8 local_e8;
  float local_e0;
  longlong local_d8;
  float local_d0;
  int local_c8;
  undefined8 local_c0;
  undefined8 uStack_b8;
  int local_b0;
  longlong local_a8;
  float local_a0;
  undefined local_98 [16];
  undefined local_88 [72];
  
  if (DAT_181ff1abe == '\0') {
    thunk_FUN_180203190(DAT_1817dfbfc);
    DAT_181ff1abe = '\x01';
  }
  local_e8 = 0;
  local_e0 = 0.0;
  local_a8 = 0;
  local_a0 = 0.0;
  local_d8 = 0;
  local_d0 = 0.0;
  lVar13 = thunk_FUN_180207de0(DAT_1822a72d0);
  FUN_1810f2350(lVar13,DAT_1822ad4a0);
  local_148 = *(longlong *)param_2;
  local_140 = param_2[2];
  local_110 = lVar13;
  if (((*(byte *)(DAT_1822ab970 + 0x12f) & 2) != 0) && (*(int *)(DAT_1822ab970 + 0xe0) == 0)) {
    il2cpp_runtime_class_init();
  }
  local_108 = *(longlong *)param_3;
  local_100 = param_3[2];
  cVar7 = FUN_18154f810(&local_148,&local_108,0);
  if (cVar7 != '\0') {
    return local_110;
  }
  if (param_1 != (longlong *)0x0) {
    lVar15 = *param_1;
    lVar13 = *(longlong *)param_2;
    uVar19 = 0;
    fVar26 = param_2[2];
    if (*(ushort *)(lVar15 + 0x126) != 0) {
      do {
        if (*(longlong *)(*(longlong *)(lVar15 + 0xb0) + (ulonglong)uVar19 * 0x10) == DAT_1822fc9e0)
        {
          puVar14 = (undefined8 *)
                    (((ulonglong)
                      (*(int *)(*(longlong *)(lVar15 + 0xb0) + 8 + (ulonglong)uVar19 * 0x10) + 2) +
                     0x13) * 0x10 + lVar15);
          goto LAB_180c513de;
        }
        uVar19 = uVar19 + 1;
      } while (uVar19 < *(ushort *)(lVar15 + 0x126));
    }
    puVar14 = (undefined8 *)FUN_1801f9690(param_1,DAT_1822fc9e0,2);
LAB_180c513de:
    local_100 = param_3[2];
    local_108 = *(longlong *)param_3;
    local_148 = lVar13;
    local_140 = fVar26;
    lVar13 = (*(code *)*puVar14)(param_1,&local_148,&local_108,puVar14[1]);
    local_108 = lVar13;
    if (lVar13 != 0) {
      iVar12 = *(int *)(lVar13 + 0x18);
      local_118 = iVar12;
      if (iVar12 == 0) {
        FUN_180d9d940(0);
      }
      lVar15 = *(longlong *)(*(longlong *)(lVar13 + 0x10) + 0x20);
      if (lVar15 != 0) {
        uVar8 = thunk_FUN_1801db2d0(lVar15,0,0);
        if (((*(byte *)(DAT_1822ab7c8 + 0x12f) & 2) != 0) && (*(int *)(DAT_1822ab7c8 + 0xe0) == 0))
        {
          il2cpp_runtime_class_init();
        }
        iVar9 = FUN_18104eaa0(uVar8,0x40);
        local_c8 = iVar9;
        if (*(int *)(lVar13 + 0x18) == 0) {
          FUN_180d9d940(0);
        }
        lVar15 = *(longlong *)(*(longlong *)(lVar13 + 0x10) + 0x20);
        if (lVar15 != 0) {
          iVar23 = 1;
          uVar8 = thunk_FUN_1801db2d0(lVar15,1,0);
          iVar10 = FUN_18104eaa0(uVar8,0x40,0);
          lVar15 = *param_1;
          uVar21 = 0;
          if (*(ushort *)(lVar15 + 0x126) != 0) {
            do {
              if (*(longlong *)(*(longlong *)(lVar15 + 0xb0) + uVar21 * 0x10) == DAT_1822fc9e0) {
                puVar14 = (undefined8 *)
                          (((ulonglong)
                            (*(int *)(*(longlong *)(lVar15 + 0xb0) + 8 + uVar21 * 0x10) + 0x11) +
                           0x13) * 0x10 + lVar15);
                goto LAB_180c5150c;
              }
              uVar19 = (short)uVar21 + 1;
              uVar21 = (ulonglong)uVar19;
            } while (uVar19 < *(ushort *)(lVar15 + 0x126));
          }
          puVar14 = (undefined8 *)FUN_1801f9690(param_1,DAT_1822fc9e0,0x11);
LAB_180c5150c:
          puVar14 = (undefined8 *)(*(code *)*puVar14)(local_98,param_1,puVar14[1]);
          local_c0 = *puVar14;
          uStack_b8 = puVar14[1];
          fVar26 = (float)FUN_181062850(&local_c0,0);
          FUN_180ab8ea0(&local_c0,fVar26 * DAT_181afb090,0);
          fVar26 = (float)FUN_1810627a0(&local_c0,0);
          FUN_180b77090(&local_c0,fVar26 * DAT_181afb090,0);
          FUN_1805c4f50(&local_c0,0,0);
          uVar27 = FUN_1810627a0(&local_c0,0);
          FUN_1805c4f40(&local_c0,uVar27,0);
          uVar27 = FUN_181062850(&local_c0,0);
          uVar8 = FUN_1810627a0(&local_c0,0);
          uVar30 = 0;
          FUN_18154f0a0(&local_e8,uVar27,uVar8,0,0);
          iVar11 = FUN_18104ea90(((int)(float)local_e8 - iVar9 / 2) + (int)*param_2,0,0);
          local_140 = param_2[2];
          local_148._4_4_ = (float)((ulonglong)*(longlong *)param_2 >> 0x20);
          iVar20 = (int)local_148._4_4_;
          local_148 = *(longlong *)param_2;
          local_114 = iVar11;
          local_138 = FUN_18104ea90(((int)local_e8._4_4_ - iVar10 / 2) + iVar20,0,0);
          if (*(int *)(lVar13 + 0x18) == 0) {
            FUN_180d9d940(0);
          }
          lVar15 = *(longlong *)(*(longlong *)(lVar13 + 0x10) + 0x20);
          if (lVar15 != 0) {
            iVar20 = thunk_FUN_1801db2d0(lVar15,0,0);
            if (iVar20 < iVar11 + iVar9) {
              if (*(int *)(lVar13 + 0x18) == 0) {
                FUN_180d9d940(0);
              }
              lVar15 = *(longlong *)(*(longlong *)(lVar13 + 0x10) + 0x20);
              if (lVar15 == 0) goto LAB_180c520e1;
              local_114 = thunk_FUN_1801db2d0(lVar15,0,0);
              local_114 = local_114 - iVar9;
            }
            if (*(int *)(lVar13 + 0x18) == 0) {
              FUN_180d9d940(0);
            }
            lVar15 = *(longlong *)(*(longlong *)(lVar13 + 0x10) + 0x20);
            if (lVar15 != 0) {
              iVar11 = thunk_FUN_1801db2d0(lVar15,1,0);
              if (iVar11 < local_138 + iVar10) {
                if (*(int *)(lVar13 + 0x18) == 0) {
                  FUN_180d9d940(0);
                }
                lVar15 = *(longlong *)(*(longlong *)(lVar13 + 0x10) + 0x20);
                if (lVar15 == 0) goto LAB_180c520e1;
                local_138 = thunk_FUN_1801db2d0(lVar15,1,0);
                local_138 = local_138 - iVar10;
              }
              lVar15 = thunk_FUN_180207de0(DAT_1822c8a10);
              local_148 = lVar15;
              FUN_18026d8f0(lVar15,0);
              if (lVar15 != 0) {
                *(longlong *)(lVar15 + 0x10) = lVar13;
                thunk_FUN_180239040((longlong *)(lVar15 + 0x10),lVar13);
                local_f0 = local_e0;
                local_f8 = local_e8;
                *(int *)(lVar15 + 0x18) = iVar9;
                *(int *)(lVar15 + 0x1c) = iVar10;
                *(int *)(lVar15 + 0x20) = iVar12;
                local_168 = *(longlong *)param_2;
                local_160 = param_2[2];
                if (((*(byte *)(DAT_1822ab970 + 0x12f) & 2) != 0) &&
                   (*(int *)(DAT_1822ab970 + 0xe0) == 0)) {
                  il2cpp_runtime_class_init();
                }
                puVar14 = (undefined8 *)FUN_18154f770(&local_158,&local_168,&local_f8,0);
                lVar15 = local_148;
                *(undefined8 *)(local_148 + 0x24) = *puVar14;
                *(undefined4 *)(local_148 + 0x2c) = *(undefined4 *)(puVar14 + 1);
                local_160 = local_e0;
                local_168 = local_e8;
                local_f8 = *(longlong *)param_3;
                local_f0 = param_3[2];
                puVar14 = (undefined8 *)FUN_18154f770(&local_158,&local_f8,&local_168,0);
                *(undefined8 *)(lVar15 + 0x30) = *puVar14;
                *(undefined4 *)(lVar15 + 0x38) = *(undefined4 *)(puVar14 + 1);
                *(int *)(lVar15 + 0x40) = local_114;
                *(int *)(lVar15 + 0x44) = local_138;
                *(undefined4 *)(lVar15 + 0x3c) = 0;
                *(char *)(lVar15 + 0x48) = param_4;
                local_160 = *(float *)(lVar15 + 0x2c);
                local_168 = *(longlong *)(lVar15 + 0x24);
                if (*(int *)(lVar13 + 0x18) <= (int)local_160) {
LAB_180c520e7:
                  uVar27 = FUN_18154ec70(param_2,DAT_1822f8638,0);
                  uVar27 = FUN_1810886f0(DAT_1822bf190,uVar27,0);
                  uVar18 = thunk_FUN_180207de0(DAT_1822ec318);
                  FUN_180c4e820(uVar18,uVar27,0);
                  FUN_18023bce0(uVar18,DAT_1822a9d98);
                  pcVar3 = (code *)swi(3);
                  lVar13 = (*pcVar3)();
                  return lVar13;
                }
                local_160 = *(float *)(lVar15 + 0x2c);
                if (*(int *)(lVar13 + 0x18) == 0) {
                  FUN_180d9d940(0);
                }
                lVar16 = *(longlong *)(*(longlong *)(lVar13 + 0x10) + 0x20);
                if (lVar16 != 0) {
                  iVar12 = thunk_FUN_1801db2d0(lVar16,0,0);
                  if (iVar12 <= (int)(float)local_168) goto LAB_180c520e7;
                  local_168 = *(longlong *)(lVar15 + 0x24);
                  local_160 = *(float *)(lVar15 + 0x2c);
                  if (*(int *)(lVar13 + 0x18) == 0) {
                    FUN_180d9d940(0);
                  }
                  lVar13 = *(longlong *)(*(longlong *)(lVar13 + 0x10) + 0x20);
                  if (lVar13 != 0) {
                    iVar12 = thunk_FUN_1801db2d0(lVar13,1,0);
                    if (iVar12 <= (int)local_168._4_4_) goto LAB_180c520e7;
                    lVar13 = thunk_FUN_180207de0(DAT_1822c89e0);
                    if (param_4 == '\0') {
                      FUN_1802e9aa0(lVar13,0,DAT_1822eda68,DAT_1822a62d0);
                      lVar16 = thunk_FUN_180207de0(DAT_1822c8990);
                      uVar27 = DAT_1822e1970;
                    }
                    else {
                      FUN_1802e9aa0(lVar13,0,DAT_1822edab0,DAT_1822a62d0);
                      lVar16 = thunk_FUN_180207de0(DAT_1822c8990);
                      uVar27 = DAT_1822e19b0;
                    }
                    FUN_1802e9aa0(lVar16,0,uVar27,DAT_1822a29c0);
                    if (lVar13 != 0) {
                      lVar13 = FUN_18151a4b0(lVar13,lVar15,DAT_182302cd0);
                      local_128 = *(longlong *)(lVar15 + 0x30);
                      local_160 = *(float *)(lVar15 + 0x38);
                      local_168 = local_128;
                      local_120 = local_160;
                      local_f8 = local_128;
                      local_f0 = local_160;
                      if (lVar13 != 0) {
                        local_168._4_4_ = (float)((ulonglong)local_128 >> 0x20);
                        iVar12 = (int)local_168._4_4_;
                        local_f8._0_4_ = (float)local_128;
                        iVar11 = (int)(float)local_f8;
                        FUN_1801566c0(lVar13,(longlong)(int)local_160,(longlong)(iVar11 - local_114)
                                      ,(longlong)(iVar12 - local_138),CONCAT44(uVar30,1));
                        bVar4 = true;
                        bVar5 = true;
                        iVar12 = *(int *)(lVar15 + 0x3c);
                        do {
                          local_b0 = iVar12;
                          iVar11 = 0;
                          iVar12 = local_118;
                          if (0 < local_118) {
                            do {
                              iVar20 = 0;
                              if (0 < iVar9) {
                                do {
                                  iVar9 = 0;
                                  if (0 < iVar10) {
                                    do {
                                      bVar4 = bVar5;
                                      iVar12 = FUN_180156650(lVar13,(longlong)iVar11,
                                                             (longlong)iVar20,(longlong)iVar9);
                                      if (iVar12 == iVar23) {
                                        if (lVar16 == 0) goto LAB_180c520e1;
                                        cVar7 = FUN_180ffd8a0(lVar16,lVar13,local_148,iVar11,iVar20,
                                                              iVar9,iVar23,DAT_182302690);
                                        if (cVar7 != '\0') {
                                          bVar4 = false;
                                          iVar9 = iVar10;
                                          iVar20 = local_c8;
                                          iVar11 = local_118;
                                        }
                                      }
                                      iVar9 = iVar9 + 1;
                                      iVar12 = local_118;
                                      bVar5 = bVar4;
                                    } while (iVar9 < iVar10);
                                  }
                                  iVar20 = iVar20 + 1;
                                  iVar9 = local_c8;
                                } while (iVar20 < local_c8);
                              }
                              iVar11 = iVar11 + 1;
                              lVar15 = local_148;
                            } while (iVar11 < iVar12);
                          }
                          lVar6 = local_108;
                          uVar27 = DAT_1822c8968;
                          if ((bool)(bVar4 & *(int *)(lVar15 + 0x3c) == local_b0)) {
                            local_158._0_4_ = (float)*(undefined8 *)(lVar15 + 0x30);
                            iVar9 = (int)(float)local_158;
                            local_150 = param_3[2];
                            iVar12 = (int)local_150;
                            local_158._4_4_ =
                                 (float)((ulonglong)*(undefined8 *)(lVar15 + 0x30) >> 0x20);
                            iVar10 = (int)local_158._4_4_;
                            local_158 = *(undefined8 *)param_3;
                            while( true ) {
                              iVar12 = iVar12 + -1;
                              if (iVar12 < 0) {
                                return local_110;
                              }
                              lVar13 = FUN_1800ddc20(lVar6,iVar12,DAT_1822a64a0);
                              if (lVar13 == 0) break;
                              iVar23 = FUN_1800dcca0(lVar13,(longlong)iVar9,(longlong)iVar10);
                              if (0 < iVar23) {
                                param_3[2] = (float)iVar12;
                                local_150 = param_3[2];
                                local_158 = *(undefined8 *)param_3;
                                local_128 = *(longlong *)param_2;
                                local_120 = param_2[2];
                                lVar13 = MapRouteSearcher__Search
                                                   (param_1,&local_128,&local_158,param_4,0);
                                return lVar13;
                              }
                            }
                            goto LAB_180c520e1;
                          }
                          iVar23 = iVar23 + 1;
                          iVar12 = *(int *)(lVar15 + 0x3c);
                        } while (bVar4);
                        fVar26 = *(float *)(lVar15 + 0x2c);
                        *(undefined8 *)param_2 = *(undefined8 *)(lVar15 + 0x24);
                        param_2[2] = fVar26;
                        fVar1 = *(float *)(lVar15 + 0x38);
                        *(undefined8 *)param_3 = *(undefined8 *)(lVar15 + 0x30);
                        fVar26 = *param_2;
                        param_3[2] = fVar1;
                        fVar1 = *param_3;
                        fVar28 = (float)local_114;
                        fVar29 = (float)local_138;
                        *param_2 = fVar26 - fVar28;
                        fVar26 = param_2[1];
                        *param_3 = fVar1 - fVar28;
                        param_2[1] = fVar26 - fVar29;
                        param_3[1] = param_3[1] - fVar29;
                        lVar16 = thunk_FUN_180207de0(uVar27);
                        FUN_180c5bd00(lVar16,0);
                        if (lVar16 != 0) {
                          *(undefined8 *)(lVar16 + 0x10) = *(undefined8 *)param_2;
                          *(float *)(lVar16 + 0x18) = param_2[2];
                          local_160 = param_2[2];
                          local_168 = *(longlong *)param_2;
                          local_128._4_4_ = (float)((ulonglong)local_168 >> 0x20);
                          iVar12 = (int)local_128._4_4_;
                          local_128 = local_168;
                          local_120 = local_160;
                          uVar8 = FUN_180156650(lVar13,(longlong)(int)local_160,
                                                (longlong)(int)*param_2,(longlong)iVar12);
                          local_120 = param_3[2];
                          local_128 = *(longlong *)param_3;
                          uVar21 = 0;
                          cVar7 = MapRouteSearcher__SearchShortestRoute
                                            (&local_110,lVar13,lVar15,&local_128,lVar16,uVar8,0);
                          if (cVar7 == '\0') {
                            if (((*(byte *)(DAT_1822abc68 + 0x12f) & 2) != 0) &&
                               (*(int *)(DAT_1822abc68 + 0xe0) == 0)) {
                              il2cpp_runtime_class_init();
                            }
                            FUN_181107bf0(DAT_1822bf150,0);
                            return local_110;
                          }
                          FUN_18154f0a0(&local_a8,fVar28,fVar29,0,0);
                          if (local_110 != 0) {
                            iVar12 = *(int *)(local_110 + 0x18);
                            uVar22 = uVar21;
                            uVar25 = uVar21;
                            if (0 < (longlong)iVar12) {
                              do {
                                lVar13 = local_110;
                                if (local_110 == 0) goto LAB_180c520e1;
                                uVar24 = (uint)uVar22;
                                if (*(uint *)(local_110 + 0x18) <= uVar24) {
                                  FUN_180d9d940(0);
                                }
                                fVar1 = local_e0;
                                lVar6 = local_e8;
                                lVar16 = *(longlong *)(lVar13 + 0x10);
                                lVar15 = *(longlong *)(lVar16 + 0x20 + uVar21);
                                fVar26 = *(float *)(lVar16 + 0x28 + uVar21);
                                if (((*(byte *)(DAT_1822ab970 + 0x12f) & 2) != 0) &&
                                   (*(int *)(DAT_1822ab970 + 0xe0) == 0)) {
                                  il2cpp_runtime_class_init();
                                }
                                local_128 = lVar6;
                                local_120 = fVar1;
                                local_168 = lVar15;
                                local_160 = fVar26;
                                plVar17 = (longlong *)
                                          FUN_18154f9d0(local_88,&local_168,&local_128,0);
                                local_f8 = *plVar17;
                                local_f0 = *(float *)(plVar17 + 1);
                                FUN_1810f3930(lVar13,uVar22,&local_f8,DAT_1822ad350);
                                lVar13 = local_110;
                                if (local_110 == 0) goto LAB_180c520e1;
                                if (*(uint *)(local_110 + 0x18) <= uVar24) {
                                  FUN_180d9d940(0);
                                }
                                local_100 = local_a0;
                                lVar15 = *(longlong *)(lVar13 + 0x10);
                                local_108 = local_a8;
                                local_148 = *(longlong *)(lVar15 + 0x20 + uVar21);
                                local_140 = *(float *)(lVar15 + 0x28 + uVar21);
                                puVar14 = (undefined8 *)
                                          FUN_18154f770(local_98,&local_148,&local_108,0);
                                local_158 = *puVar14;
                                local_150 = *(float *)(puVar14 + 1);
                                FUN_1810f3930(lVar13,uVar22,&local_158);
                                uVar22 = (ulonglong)(uVar24 + 1);
                                uVar25 = uVar25 + 1;
                                uVar21 = uVar21 + 0xc;
                              } while ((longlong)uVar25 < (longlong)iVar12);
                            }
                            lVar15 = thunk_FUN_180207de0(DAT_1822a72d0);
                            FUN_1810f2350(lVar15,DAT_1822ad4a0);
                            lVar13 = local_110;
                            if (local_110 != 0) {
                              if (*(int *)(local_110 + 0x18) == 0) {
                                FUN_180d9d940(0);
                              }
                              local_158 = *(undefined8 *)(*(longlong *)(lVar13 + 0x10) + 0x20);
                              local_150 = *(float *)(*(longlong *)(lVar13 + 0x10) + 0x28);
                              puVar14 = (undefined8 *)
                                        FUN_1800dd8b0(local_98,3,DAT_1822fc9e0,param_1,&local_158);
                              if (lVar15 != 0) {
                                local_158 = *puVar14;
                                local_150 = *(float *)(puVar14 + 1);
                                FUN_1810e93e0(lVar15,&local_158,DAT_1822ad428);
                                if (local_110 != 0) {
                                  iVar12 = *(int *)(local_110 + 0x18);
                                  if (iVar12 < 2) {
                                    return lVar15;
                                  }
                                  uVar24 = 1;
                                  lVar16 = 1;
                                  lVar13 = 0xc;
                                  while (lVar6 = local_110, local_110 != 0) {
                                    if (*(uint *)(local_110 + 0x18) <= uVar24) {
                                      FUN_180d9d940(0);
                                    }
                                    lVar2 = *param_1;
                                    uVar27 = *(undefined8 *)
                                              (*(longlong *)(lVar6 + 0x10) + 0x20 + lVar13);
                                    fVar26 = *(float *)(*(longlong *)(lVar6 + 0x10) + 0x28 + lVar13)
                                    ;
                                    uVar19 = 0;
                                    if (*(ushort *)(lVar2 + 0x126) != 0) {
                                      do {
                                        if (*(longlong *)
                                             (*(longlong *)(lVar2 + 0xb0) + (ulonglong)uVar19 * 0x10
                                             ) == DAT_1822fc9e0) {
                                          puVar14 = (undefined8 *)
                                                    (((ulonglong)
                                                      (*(int *)(*(longlong *)(lVar2 + 0xb0) + 8 +
                                                               (ulonglong)uVar19 * 0x10) + 3) + 0x13
                                                     ) * 0x10 + lVar2);
                                          goto LAB_180c51e7c;
                                        }
                                        uVar19 = uVar19 + 1;
                                      } while (uVar19 < *(ushort *)(lVar2 + 0x126));
                                    }
                                    puVar14 = (undefined8 *)FUN_1801f9690(param_1,DAT_1822fc9e0,3);
LAB_180c51e7c:
                                    local_158 = uVar27;
                                    local_150 = fVar26;
                                    plVar17 = (longlong *)
                                              (*(code *)*puVar14)(local_98,param_1,&local_158,
                                                                  puVar14[1]);
                                    local_d8 = *plVar17;
                                    fVar26 = *(float *)(plVar17 + 1);
                                    local_108._4_4_ = (float)((ulonglong)local_d8 >> 0x20);
                                    fVar1 = local_108._4_4_;
                                    fVar28 = (float)local_d8;
                                    local_108 = local_d8;
                                    local_100 = fVar26;
                                    local_d0 = fVar26;
                                    FUN_1809c04c0(&local_148,lVar15,DAT_1822b47e0);
                                    if (((float)local_148 == fVar28) && (local_148._4_4_ == fVar1))
                                    {
                                      if (fVar26 < local_140) {
                                        local_128 = local_d8;
                                        local_120 = local_d0;
                                        FUN_1810f3930(lVar15,*(int *)(lVar15 + 0x18) + -1,&local_128
                                                      ,DAT_1822ad350);
                                      }
                                    }
                                    else {
                                      local_168 = local_d8;
                                      local_160 = local_d0;
                                      FUN_1810e93e0(lVar15,&local_168,DAT_1822ad428);
                                    }
                                    uVar24 = uVar24 + 1;
                                    lVar16 = lVar16 + 1;
                                    lVar13 = lVar13 + 0xc;
                                    if (iVar12 <= lVar16) {
                                      return lVar15;
                                    }
                                  }
                                }
                              }
                            }
                          }
                        }
                      }
                    }
                  }
                }
              }
            }
          }
        }
      }
    }
  }
LAB_180c520e1:
  FUN_18023bd10();
  pcVar3 = (code *)swi(3);
  lVar13 = (*pcVar3)();
  return lVar13;
}



/********************************************************************/
/* MapRouteSearcher$$UpdateRouteMapCellStep
 * RVA: 0xC52140
 * Address: 0x180C52140
 *******************************************************************/


ulonglong MapRouteSearcher__UpdateRouteMapCellStep
                    (longlong param_1,longlong param_2,int param_3,int param_4,int param_5,
                    float *param_6,int param_7)

{
  code *pcVar1;
  ulonglong uVar2;
  uint uVar3;
  uint uVar4;
  uint uVar5;
  float local_38;
  float fStack_34;
  
  uVar2 = (ulonglong)(uint)param_6[2];
  fStack_34 = (float)((ulonglong)*(undefined8 *)param_6 >> 0x20);
  uVar4 = (int)param_6[2] + param_3;
  uVar5 = (int)fStack_34 + param_5;
  uVar3 = (int)*param_6 + param_4;
  if (-1 < (int)uVar3) {
    if (param_2 == 0) {
LAB_180c5228c:
      FUN_18023bd10();
      pcVar1 = (code *)swi(3);
      uVar2 = (*pcVar1)();
      return uVar2;
    }
    if (((((int)uVar3 < *(int *)(param_2 + 0x18)) && (-1 < (int)uVar5)) &&
        ((int)uVar5 < *(int *)(param_2 + 0x1c))) &&
       ((-1 < (int)uVar4 && ((int)uVar4 < *(int *)(param_2 + 0x20))))) {
      if (param_1 == 0) goto LAB_180c5228c;
      uVar2 = FUN_180156650(*(undefined8 *)param_6,(longlong)(int)uVar4,(longlong)(int)uVar3,
                            (longlong)(int)uVar5);
      if ((int)uVar2 == 0) {
        FUN_1801566c0(param_1,(longlong)(int)uVar4,(longlong)(int)uVar3,(longlong)(int)uVar5,
                      param_7 + 1);
        *(int *)(param_2 + 0x3c) = *(int *)(param_2 + 0x3c) + 1;
        uVar2 = (ulonglong)(uint)(int)*(float *)(param_2 + 0x2c);
        if (uVar4 == (int)*(float *)(param_2 + 0x2c)) {
          local_38 = (float)*(undefined8 *)(param_2 + 0x24);
          uVar4 = (int)local_38 - *(int *)(param_2 + 0x40);
          uVar2 = (ulonglong)uVar4;
          if (uVar3 == uVar4) {
            fStack_34 = (float)((ulonglong)*(undefined8 *)(param_2 + 0x24) >> 0x20);
            uVar3 = (int)fStack_34 - *(int *)(param_2 + 0x44);
            uVar2 = (ulonglong)uVar3;
            if (uVar5 == uVar3) {
              return CONCAT71((uint7)(uint3)(uVar3 >> 8),1);
            }
          }
        }
      }
    }
  }
  return uVar2 & 0xffffffffffffff00;
}

