/*
 * FF3 Decompiled Functions - Magic/Ability Menu
 * Generated by Ghidra headless analysis
 * Program: GameAssembly.dll
 * Image Base: 0x180000000
 * IL2CPP types applied: True
 *
 * Purpose: Understanding magic menu data flow for screen reader accessibility
 *
 * Key classes:
 *   - AbilityContentListController: Main spell list controller
 *   - AbilityCommandController: Command menu (Use/Remove/Exchange/Memorize)
 *   - BattleAbilityInfomationContentController: Individual spell item
 *   - OwnedAbility: Spell data wrapper
 */


/====================================================================/
/* Ability
 ===================================================================/

/********************************************************************/
/* Ability$$get_AbilityLv
 * RVA: 0xF54780
 * Address: 0x180F54780
 *******************************************************************/

/* DECOMPILATION FAILED: Could not create function at 0x180F54780 */

/********************************************************************/
/* Ability$$get_TypeId
 * RVA: 0xF54790
 * Address: 0x180F54790
 *******************************************************************/


void Ability_get_TypeId(undefined8 param_1,longlong param_2)

{
  FUN_1805e70c0(param_1,param_2 + 8,DAT_1822d7718);
  return;
}



/====================================================================/
/* AbilityCommandContentData
 ===================================================================/

/********************************************************************/
/* AbilityCommandContentData$$get_Id
 * RVA: 0x6BDF30
 * Address: 0x1806BDF30
 *******************************************************************/


void AbilityCommandContentData_get_Id(void)

{
  undefined8 uVar1;
  code *pcVar2;
  char in_AL;
  longlong unaff_RBP;
  longlong unaff_RSI;
  int unaff_EDI;
  longlong unaff_R14;
  
  while (in_AL != '\0') {
    uVar1 = *(undefined8 *)(unaff_RBP + 0x28);
    FUN_18159fd20(uVar1,1,0);
    FUN_1815a02a0(uVar1);
    in_AL = FUN_180a4ee80(unaff_RBP + 0x18,DAT_1822c9908);
  }
  *(undefined4 *)(unaff_R14 + 4 + (longlong)unaff_EDI * 4) = 0x9b;
  FUN_18026d8f0(unaff_RBP + 0x18,DAT_1822be2a0);
  if (unaff_RSI == 0) {
    return;
  }
  FUN_18023bce0();
  pcVar2 = (code *)swi(3);
  (*pcVar2)();
  return;
}



/====================================================================/
/* AbilityCommandController
 ===================================================================/

/********************************************************************/
/* AbilityCommandController$$GetCurrentAbilityCommandId
 * RVA: 0x681BA0
 * Address: 0x180681BA0
 *******************************************************************/


ulonglong FUN_180681ba0(longlong param_1)

{
  code *pcVar1;
  char cVar2;
  longlong lVar3;
  ulonglong uVar4;
  
  if (DAT_181fedf5b == '\0') {
    thunk_FUN_180203190(DAT_1817ca3b8);
    DAT_181fedf5b = '\x01';
  }
  cVar2 = FUN_180afb340(*(undefined8 *)(param_1 + 0x48),DAT_1822c5710);
  if (cVar2 == '\0') {
    return 0;
  }
  if (*(longlong *)(param_1 + 0x58) != 0) {
    lVar3 = FUN_180763cb0(*(undefined8 *)(param_1 + 0x48),
                          *(undefined4 *)(*(longlong *)(param_1 + 0x58) + 0x18),DAT_1822b86b8);
    if ((lVar3 != 0) && (*(longlong *)(lVar3 + 0x18) != 0)) {
      return (ulonglong)*(uint *)(*(longlong *)(lVar3 + 0x18) + 0x10);
    }
  }
  FUN_18023bd10();
  pcVar1 = (code *)swi(3);
  uVar4 = (*pcVar1)();
  return uVar4;
}



/********************************************************************/
/* AbilityCommandController$$SelectCommandByIndex
 * RVA: 0x6821F0
 * Address: 0x1806821F0
 *******************************************************************/


void FUN_1806821f0(longlong param_1,undefined4 param_2)

{
  uint uVar1;
  undefined8 uVar2;
  undefined8 uVar3;
  longlong lVar4;
  code *pcVar5;
  int iVar6;
  longlong lVar7;
  longlong *plVar8;
  
  if (DAT_181fedf5c == '\0') {
    thunk_FUN_180203190(DAT_1817ca494);
    DAT_181fedf5c = '\x01';
  }
  uVar2 = *(undefined8 *)(param_1 + 0x48);
  if (((*(byte *)(DAT_1822c49f0 + 0x12f) & 2) != 0) && (*(int *)(DAT_1822c49f0 + 0xe0) == 0)) {
    il2cpp_runtime_class_init();
  }
  lVar7 = *(longlong *)(*(longlong *)(DAT_1822c49f0 + 0xb8) + 8);
  if (lVar7 == 0) {
    if (((*(byte *)(DAT_1822c49f0 + 0x12f) & 2) != 0) && (*(int *)(DAT_1822c49f0 + 0xe0) == 0)) {
      il2cpp_runtime_class_init();
    }
    uVar3 = **(undefined8 **)(DAT_1822c49f0 + 0xb8);
    lVar7 = thunk_FUN_180207de0(DAT_1822c4ab8);
    FUN_1802e9aa0(lVar7,uVar3,DAT_1822e1060,DAT_1822a5e88);
    plVar8 = (longlong *)(*(longlong *)(DAT_1822c49f0 + 0xb8) + 8);
    *plVar8 = lVar7;
    thunk_FUN_180239040(plVar8,lVar7);
  }
  iVar6 = FUN_180bda680(uVar2,lVar7,DAT_1822f2bb0);
  if (((*(byte *)(DAT_1822ab7c8 + 0x12f) & 2) != 0) && (*(int *)(DAT_1822ab7c8 + 0xe0) == 0)) {
    il2cpp_runtime_class_init();
  }
  iVar6 = FUN_18104eaa0(iVar6 + -1,param_2,0);
  if (iVar6 == -1) {
    return;
  }
  if (*(longlong *)(param_1 + 0x58) != 0) {
    *(int *)(*(longlong *)(param_1 + 0x58) + 0x18) = iVar6;
    FUN_180682510(param_1,0);
    lVar7 = *(longlong *)(param_1 + 0x30);
    if (lVar7 == 0) {
      return;
    }
    if ((*(longlong *)(param_1 + 0x58) != 0) && (lVar4 = *(longlong *)(param_1 + 0x48), lVar4 != 0))
    {
      uVar1 = *(uint *)(*(longlong *)(param_1 + 0x58) + 0x18);
      if (*(uint *)(lVar4 + 0x18) <= uVar1) {
        FUN_180d9d940(0);
      }
      lVar4 = *(longlong *)(*(longlong *)(lVar4 + 0x10) + 0x20 + (longlong)(int)uVar1 * 8);
      if (((lVar4 != 0) && (lVar4 = *(longlong *)(lVar4 + 0x18), lVar4 != 0)) &&
         (*(longlong *)(param_1 + 0x58) != 0)) {
        FUN_18101b070(lVar7,*(undefined4 *)(lVar4 + 0x10),
                      *(undefined4 *)(*(longlong *)(param_1 + 0x58) + 0x18),DAT_1822ec768);
        return;
      }
    }
  }
  FUN_18023bd10();
  pcVar5 = (code *)swi(3);
  (*pcVar5)();
  return;
}



/********************************************************************/
/* AbilityCommandController$$SetAbilityData
 * RVA: 0x6823B0
 * Address: 0x1806823B0
 *******************************************************************/


void AbilityCommandController_SetAbilityData(longlong param_1,longlong param_2)

{
  undefined8 uVar1;
  code *pcVar2;
  longlong lVar3;
  undefined8 uVar4;
  
  if (DAT_181fedf55 == '\0') {
    thunk_FUN_180203190(DAT_1817ca4bc);
    DAT_181fedf55 = '\x01';
  }
  if (((*(byte *)(DAT_1822fcdd0 + 0x12f) & 2) != 0) && (*(int *)(DAT_1822fcdd0 + 0xe0) == 0)) {
    il2cpp_runtime_class_init();
  }
  lVar3 = FUN_180f6c390(DAT_1822d9378);
  if (param_2 != 0) {
    uVar4 = FUN_180664350(param_2,0);
    if (lVar3 != 0) {
      uVar4 = FUN_1802c0ff0(lVar3,uVar4,1,0);
      if (DAT_181fedf58 == '\0') {
        thunk_FUN_180203190(DAT_1817ca56c);
        DAT_181fedf58 = '\x01';
      }
      uVar1 = *(undefined8 *)(param_1 + 0x40);
      if (((*(byte *)(DAT_1822fd930 + 0x12f) & 2) != 0) && (*(int *)(DAT_1822fd930 + 0xe0) == 0)) {
        il2cpp_runtime_class_init();
      }
      FUN_18043d670(uVar1,uVar4,0,0);
      if (DAT_181fedf5a == '\0') {
        thunk_FUN_180203190(DAT_1817ca524);
        DAT_181fedf5a = '\x01';
      }
      lVar3 = *(longlong *)(param_1 + 0x40);
      if (((*(byte *)(DAT_1822fd8c0 + 0x12f) & 2) != 0) && (*(int *)(DAT_1822fd8c0 + 0xe0) == 0)) {
        il2cpp_runtime_class_init(DAT_1822fd8c0);
      }
      if (lVar3 != 0) {
        FUN_18043dd30(lVar3,*(undefined4 *)(*(longlong *)(DAT_1822fd8c0 + 0xb8) + 8),0);
        return;
      }
    }
  }
  FUN_18023bd10();
  pcVar2 = (code *)swi(3);
  (*pcVar2)();
  return;
}



/********************************************************************/
/* AbilityCommandController$$SetFocus_CommandId
 * RVA: 0x682800
 * Address: 0x180682800
 *******************************************************************/


void FUN_180682800(longlong param_1,undefined4 param_2)

{
  uint uVar1;
  longlong lVar2;
  code *pcVar3;
  char cVar4;
  longlong lVar5;
  undefined4 *puVar6;
  undefined8 uVar7;
  undefined8 uVar8;
  longlong lVar9;
  undefined4 uVar10;
  undefined4 local_68;
  undefined4 uStack_64;
  undefined4 uStack_60;
  undefined4 uStack_5c;
  undefined4 local_58;
  undefined4 uStack_54;
  undefined4 uStack_50;
  undefined4 uStack_4c;
  longlong local_48;
  undefined4 local_40;
  undefined4 uStack_3c;
  undefined4 uStack_38;
  undefined4 uStack_34;
  longlong local_30;
  
  if (DAT_181fedf4a == '\0') {
    thunk_FUN_180203190(DAT_1817ca558);
    DAT_181fedf4a = '\x01';
  }
  lVar5 = thunk_FUN_180207de0(DAT_1822c4ae8);
  FUN_18026d8f0(lVar5,0);
  if (lVar5 != 0) {
    *(undefined4 *)(lVar5 + 0x10) = param_2;
    if (*(longlong *)(param_1 + 0x48) != 0) {
      FUN_1810eb840(&local_58,*(longlong *)(param_1 + 0x48),DAT_1822ac0b8);
      local_40 = local_58;
      uStack_3c = uStack_54;
      uStack_38 = uStack_50;
      uStack_34 = uStack_4c;
      local_30 = local_48;
      while( true ) {
        cVar4 = FUN_180a4ee80(&local_40,DAT_1822ca920);
        lVar9 = local_30;
        if (cVar4 == '\0') break;
        if (local_30 == 0) goto LAB_180682b75;
        if (*(char *)(local_30 + 0x40) != '\0') {
          if (DAT_181fedf49 == '\0') {
            thunk_FUN_180203190(DAT_1817ca330);
            DAT_181fedf49 = '\x01';
          }
          uVar8 = *(undefined8 *)(lVar9 + 0x38);
          if (((*(byte *)(DAT_1822fd8c0 + 0x12f) & 2) != 0) && (*(int *)(DAT_1822fd8c0 + 0xe0) == 0)
             ) {
            il2cpp_runtime_class_init(DAT_1822fd8c0);
          }
          puVar6 = (undefined4 *)FUN_181104e30(&local_58,**(undefined4 **)(DAT_1822fd8c0 + 0xb8),0);
          local_68 = *puVar6;
          uStack_64 = puVar6[1];
          uStack_60 = puVar6[2];
          uStack_5c = puVar6[3];
          FUN_18159feb0(uVar8,&local_68);
          *(undefined *)(lVar9 + 0x40) = 0;
        }
      }
      uVar10 = 0x41;
      FUN_18026d8f0(&local_40,DAT_1822bf258);
      uVar8 = *(undefined8 *)(param_1 + 0x48);
      uVar7 = thunk_FUN_180207de0(DAT_1822c4ab8);
      FUN_1802e9aa0(uVar7,lVar5,DAT_1822e1018,DAT_1822a5e88,uVar10);
      uVar8 = FUN_180487c90(uVar8,uVar7,DAT_1822b62a0);
      lVar9 = FUN_1809bcf60(uVar8,DAT_1822b56a0);
      if ((lVar9 != 0) && (*(char *)(lVar9 + 0x40) != '\x01')) {
        if (DAT_181fedf49 == '\0') {
          thunk_FUN_180203190(DAT_1817ca330);
          DAT_181fedf49 = '\x01';
        }
        uVar8 = *(undefined8 *)(lVar9 + 0x38);
        if (((*(byte *)(DAT_1822fd8c0 + 0x12f) & 2) != 0) && (*(int *)(DAT_1822fd8c0 + 0xe0) == 0))
        {
          il2cpp_runtime_class_init(DAT_1822fd8c0);
        }
        puVar6 = (undefined4 *)
                 FUN_181104e30(&local_58,*(undefined4 *)(*(longlong *)(DAT_1822fd8c0 + 0xb8) + 8),0)
        ;
        local_68 = *puVar6;
        uStack_64 = puVar6[1];
        uStack_60 = puVar6[2];
        uStack_5c = puVar6[3];
        FUN_18159feb0(uVar8,&local_68,0);
        *(undefined *)(lVar9 + 0x40) = 1;
      }
      lVar9 = *(longlong *)(param_1 + 0x48);
      if (*(longlong *)(param_1 + 0x58) != 0) {
        uVar1 = *(uint *)(*(longlong *)(param_1 + 0x58) + 0x18);
        if (lVar9 != 0) {
          if (uVar1 < *(uint *)(lVar9 + 0x18)) {
            lVar9 = *(longlong *)(*(longlong *)(lVar9 + 0x10) + 0x20 + (longlong)(int)uVar1 * 8);
          }
          else {
            FUN_180d9d940(0);
            lVar9 = *(longlong *)(*(longlong *)(lVar9 + 0x10) + 0x20 + (longlong)(int)uVar1 * 8);
          }
          lVar2 = *(longlong *)(param_1 + 0x58);
          if (*(int *)(lVar5 + 0x10) == 0) {
            if (lVar2 != 0) {
              FUN_180433b60(lVar2,0,0);
              if ((lVar9 != 0) && (*(longlong *)(param_1 + 0x58) != 0)) {
                FUN_180433fa0(*(longlong *)(param_1 + 0x58),*(undefined8 *)(lVar9 + 0x28),0);
                lVar5 = *(longlong *)(param_1 + 0x58);
                if (lVar5 != 0) {
                  uVar8 = *(undefined8 *)(lVar9 + 0x28);
                  goto LAB_180682b11;
                }
              }
            }
          }
          else if (lVar2 != 0) {
            FUN_180433b60(lVar2,1,0);
            if ((lVar9 != 0) && (*(longlong *)(param_1 + 0x58) != 0)) {
              FUN_180433fa0(*(longlong *)(param_1 + 0x58),*(undefined8 *)(lVar9 + 0x30),0);
              lVar5 = *(longlong *)(param_1 + 0x58);
              if (lVar5 != 0) {
                uVar8 = *(undefined8 *)(lVar9 + 0x30);
LAB_180682b11:
                FUN_180433d90(lVar5,uVar8,0,0);
                return;
              }
            }
          }
        }
      }
    }
  }
  FUN_18023bd10();
LAB_180682b75:
  uVar10 = FUN_18023bd10();
  FUN_18023bce0(uVar10,0);
  pcVar3 = (code *)swi(3);
  (*pcVar3)();
  return;
}



/********************************************************************/
/* AbilityCommandController$$SetFocus_bool
 * RVA: 0x682B90
 * Address: 0x180682B90
 *******************************************************************/


void FUN_180682b90(longlong param_1,char param_2)

{
  if (*(char *)(param_1 + 0x50) != param_2) {
    FUN_180682730(param_1,param_2,0);
    *(char *)(param_1 + 0x50) = param_2;
  }
  return;
}



/********************************************************************/
/* AbilityCommandController$$UpdateController
 * RVA: 0x6836C0
 * Address: 0x1806836C0
 *******************************************************************/


void AbilityCommandController_UpdateController(longlong param_1)

{
  if (*(int *)(param_1 + 0x68) == 1) {
    FUN_180683210();
    return;
  }
  return;
}



/********************************************************************/
/* AbilityCommandController$$UpdateFocus
 * RVA: 0x6836D0
 * Address: 0x1806836D0
 *******************************************************************/


void FUN_1806836d0(longlong param_1,char param_2,undefined8 param_3,undefined8 param_4)

{
  uint uVar1;
  code *pcVar2;
  char cVar3;
  undefined4 *puVar4;
  longlong lVar5;
  longlong lVar6;
  undefined8 uVar7;
  undefined4 uVar8;
  undefined4 local_78;
  undefined4 uStack_74;
  undefined4 uStack_70;
  undefined4 uStack_6c;
  undefined4 local_68;
  undefined4 uStack_64;
  undefined4 uStack_60;
  undefined4 uStack_5c;
  longlong local_58;
  undefined4 local_50;
  undefined4 uStack_4c;
  undefined4 uStack_48;
  undefined4 uStack_44;
  longlong local_40;
  
  if (DAT_181fedf4f == '\0') {
    thunk_FUN_180203190(DAT_1817ca66c);
    DAT_181fedf4f = '\x01';
  }
  if (*(longlong *)(param_1 + 0x48) == 0) goto LAB_180683a1f;
  FUN_1810eb840(&local_68,*(longlong *)(param_1 + 0x48),DAT_1822ac0b8);
  local_50 = local_68;
  uStack_4c = uStack_64;
  uStack_48 = uStack_60;
  uStack_44 = uStack_5c;
  local_40 = local_58;
  while (cVar3 = FUN_180a4ee80(&local_50,DAT_1822ca920), lVar5 = local_40, cVar3 != '\0') {
    if (local_40 == 0) {
      uVar8 = FUN_18023bd10();
      FUN_18023bce0(uVar8,0);
      pcVar2 = (code *)swi(3);
      (*pcVar2)();
      return;
    }
    if (*(char *)(local_40 + 0x40) != '\0') {
      if (DAT_181fedf49 == '\0') {
        thunk_FUN_180203190(DAT_1817ca330);
        DAT_181fedf49 = '\x01';
      }
      uVar7 = *(undefined8 *)(lVar5 + 0x38);
      if (((*(byte *)(DAT_1822fd8c0 + 0x12f) & 2) != 0) && (*(int *)(DAT_1822fd8c0 + 0xe0) == 0)) {
        il2cpp_runtime_class_init(DAT_1822fd8c0);
      }
      puVar4 = (undefined4 *)FUN_181104e30(&local_68,**(undefined4 **)(DAT_1822fd8c0 + 0xb8),0);
      local_78 = *puVar4;
      uStack_74 = puVar4[1];
      uStack_70 = puVar4[2];
      uStack_6c = puVar4[3];
      FUN_18159feb0(uVar7,&local_78);
      *(undefined *)(lVar5 + 0x40) = 0;
    }
  }
  uVar8 = 0x34;
  FUN_18026d8f0(&local_50,DAT_1822bf258);
  if ((param_2 == '\0') || (*(char *)(param_1 + 0x51) != '\0')) {
    if (DAT_181fedf56 == '\0') {
      thunk_FUN_180203190(DAT_1817ca3f8);
      DAT_181fedf56 = '\x01';
    }
    lVar5 = *(longlong *)(param_1 + 0x48);
    if (*(longlong *)(param_1 + 0x58) == 0) goto LAB_180683a1f;
    uVar1 = *(uint *)(*(longlong *)(param_1 + 0x58) + 0x18);
    if (lVar5 == 0) goto LAB_180683a1f;
    if (*(uint *)(lVar5 + 0x18) <= uVar1) {
      FUN_180d9d940(0);
    }
    lVar5 = *(longlong *)(*(longlong *)(lVar5 + 0x10) + 0x20 + (longlong)(int)uVar1 * 8);
    if (lVar5 == 0) goto LAB_180683a1f;
    if (*(char *)(lVar5 + 0x41) == '\0') {
      return;
    }
LAB_180683955:
    lVar6 = *(longlong *)(param_1 + 0x58);
    if (lVar6 == 0) goto LAB_180683a1f;
    uVar7 = *(undefined8 *)(param_1 + 0x48);
  }
  else {
    if (((*(longlong *)(param_1 + 0x58) == 0) ||
        (lVar5 = FUN_180763cb0(*(undefined8 *)(param_1 + 0x48),
                               *(undefined4 *)(*(longlong *)(param_1 + 0x58) + 0x18),DAT_1822b86b8,
                               param_4,uVar8), lVar5 == 0)) || (*(longlong *)(lVar5 + 0x18) == 0))
    goto LAB_180683a1f;
    uVar7 = *(undefined8 *)(param_1 + 0x48);
    lVar6 = *(longlong *)(param_1 + 0x58);
    if (*(int *)(*(longlong *)(lVar5 + 0x18) + 0x10) != 3) {
      if (((lVar6 == 0) ||
          (lVar5 = FUN_180763cb0(uVar7,*(undefined4 *)(lVar6 + 0x18),DAT_1822b86b8,param_4,uVar8),
          lVar5 == 0)) || (*(longlong *)(lVar5 + 0x18) == 0)) goto LAB_180683a1f;
      if (*(int *)(*(longlong *)(lVar5 + 0x18) + 0x10) != 5) {
        return;
      }
      goto LAB_180683955;
    }
    if (lVar6 == 0) goto LAB_180683a1f;
  }
  lVar5 = FUN_180763cb0(uVar7,*(undefined4 *)(lVar6 + 0x18),DAT_1822b86b8,param_4,uVar8);
  if (lVar5 != 0) {
    if (*(char *)(lVar5 + 0x40) == '\x01') {
      return;
    }
    if (DAT_181fedf49 == '\0') {
      thunk_FUN_180203190(DAT_1817ca330);
      DAT_181fedf49 = '\x01';
    }
    uVar7 = *(undefined8 *)(lVar5 + 0x38);
    if (((*(byte *)(DAT_1822fd8c0 + 0x12f) & 2) != 0) && (*(int *)(DAT_1822fd8c0 + 0xe0) == 0)) {
      il2cpp_runtime_class_init(DAT_1822fd8c0);
    }
    puVar4 = (undefined4 *)
             FUN_181104e30(&local_68,*(undefined4 *)(*(longlong *)(DAT_1822fd8c0 + 0xb8) + 8),0);
    local_78 = *puVar4;
    uStack_74 = puVar4[1];
    uStack_70 = puVar4[2];
    uStack_6c = puVar4[3];
    FUN_18159feb0(uVar7,&local_78,0);
    *(undefined *)(lVar5 + 0x40) = 1;
    return;
  }
LAB_180683a1f:
  FUN_18023bd10();
  pcVar2 = (code *)swi(3);
  (*pcVar2)();
  return;
}



/====================================================================/
/* AbilityContentListController
 ===================================================================/

/********************************************************************/
/* AbilityContentListController$$SelectContent
 * RVA: 0x6856B0
 * Address: 0x1806856B0
 *******************************************************************/


void FUN_1806856b0(undefined8 param_1,longlong param_2)

{
  code *pcVar1;
  char cVar2;
  
  if (DAT_181fedf77 == '\0') {
    thunk_FUN_180203190(DAT_1817ca9dc);
    DAT_181fedf77 = '\x01';
  }
  if (((*(byte *)(DAT_1822abb78 + 0x12f) & 2) != 0) && (*(int *)(DAT_1822abb78 + 0xe0) == 0)) {
    il2cpp_runtime_class_init();
  }
  cVar2 = FUN_18105b7d0(param_2,0,0);
  if (cVar2 == '\0') {
    FUN_180685750(param_1,param_2,1,0,0);
    if (param_2 == 0) {
      FUN_18023bd10();
      pcVar1 = (code *)swi(3);
      (*pcVar1)();
      return;
    }
    FUN_180685930(param_1,*(undefined4 *)(param_2 + 0x18),0);
  }
  return;
}



/********************************************************************/
/* AbilityContentListController$$SelectContentByIndex
 * RVA: 0x6854B0
 * Address: 0x1806854B0
 *******************************************************************/


void FUN_1806854b0(longlong param_1,undefined4 param_2)

{
  undefined8 uVar1;
  undefined8 uVar2;
  code *pcVar3;
  char cVar4;
  int iVar5;
  longlong lVar6;
  longlong *plVar7;
  bool bVar8;
  
  if (DAT_181fedf78 == '\0') {
    thunk_FUN_180203190(DAT_1817ca9b4);
    DAT_181fedf78 = '\x01';
  }
  uVar1 = *(undefined8 *)(param_1 + 0x70);
  if (((*(byte *)(DAT_1822c4968 + 0x12f) & 2) != 0) && (*(int *)(DAT_1822c4968 + 0xe0) == 0)) {
    il2cpp_runtime_class_init();
  }
  lVar6 = *(longlong *)(*(longlong *)(DAT_1822c4968 + 0xb8) + 0x60);
  if (lVar6 == 0) {
    if (((*(byte *)(DAT_1822c4968 + 0x12f) & 2) != 0) && (*(int *)(DAT_1822c4968 + 0xe0) == 0)) {
      il2cpp_runtime_class_init();
    }
    uVar2 = **(undefined8 **)(DAT_1822c4968 + 0xb8);
    lVar6 = thunk_FUN_180207de0(DAT_1822c4828);
    FUN_1802e9aa0(lVar6,uVar2,DAT_1822e0ff0,DAT_1822a7060);
    plVar7 = (longlong *)(*(longlong *)(DAT_1822c4968 + 0xb8) + 0x60);
    *plVar7 = lVar6;
    thunk_FUN_180239040(plVar7,lVar6);
  }
  iVar5 = FUN_180bda680(uVar1,lVar6,DAT_1822f37d8);
  if (((*(byte *)(DAT_1822ab7c8 + 0x12f) & 2) != 0) && (*(int *)(DAT_1822ab7c8 + 0xe0) == 0)) {
    il2cpp_runtime_class_init();
  }
  iVar5 = FUN_18104eaa0(iVar5 + -1,param_2,0);
  if (iVar5 != -1) {
    if (*(longlong *)(param_1 + 0x50) == 0) {
LAB_1806856a1:
      FUN_18023bd10();
      pcVar3 = (code *)swi(3);
      (*pcVar3)();
      return;
    }
    bVar8 = DAT_181fedf77 == '\0';
    *(int *)(*(longlong *)(param_1 + 0x50) + 0x18) = iVar5;
    lVar6 = *(longlong *)(param_1 + 0x50);
    if (bVar8) {
      thunk_FUN_180203190(DAT_1817ca9dc);
      DAT_181fedf77 = '\x01';
    }
    if (((*(byte *)(DAT_1822abb78 + 0x12f) & 2) != 0) && (*(int *)(DAT_1822abb78 + 0xe0) == 0)) {
      il2cpp_runtime_class_init();
    }
    cVar4 = FUN_18105b7d0(lVar6,0,0);
    if (cVar4 == '\0') {
      FUN_180685750(param_1,lVar6,1,0,0);
      if (lVar6 == 0) goto LAB_1806856a1;
      FUN_180685930(param_1,*(undefined4 *)(lVar6 + 0x18),0);
    }
    if (*(longlong *)(param_1 + 0x90) != 0) {
      if (*(longlong *)(param_1 + 0x50) == 0) goto LAB_1806856a1;
      FUN_180848400(*(longlong *)(param_1 + 0x90),
                    *(undefined4 *)(*(longlong *)(param_1 + 0x50) + 0x18),DAT_1822ed490);
    }
  }
  return;
}



/********************************************************************/
/* AbilityContentListController$$SetCursor
 * RVA: 0x685750
 * Address: 0x180685750
 *******************************************************************/


void FUN_180685750(longlong param_1,longlong param_2,char param_3,int param_4)

{
  uint uVar1;
  longlong lVar2;
  code *pcVar3;
  char cVar4;
  int iVar5;
  undefined4 uVar6;
  undefined8 uVar7;
  longlong lVar8;
  undefined8 uVar9;
  undefined8 local_res10;
  
  if (DAT_181fedf76 == '\0') {
    thunk_FUN_180203190(DAT_1817caa34);
    DAT_181fedf76 = '\x01';
  }
  if (((*(byte *)(DAT_1822abb78 + 0x12f) & 2) != 0) && (*(int *)(DAT_1822abb78 + 0xe0) == 0)) {
    il2cpp_runtime_class_init();
  }
  cVar4 = FUN_18105b7d0(param_2,0,0);
  if (cVar4 != '\0') {
    return;
  }
  iVar5 = FUN_180bda4a0(*(undefined8 *)(param_1 + 0x70),DAT_1822f37f8);
  if (param_2 != 0) {
    uVar1 = *(uint *)(param_2 + 0x18);
    if (iVar5 <= (int)uVar1) {
      FUN_18159fd20(param_2,0,0);
      return;
    }
    lVar2 = *(longlong *)(param_1 + 0x70);
    if (lVar2 != 0) {
      if (*(uint *)(lVar2 + 0x18) <= uVar1) {
        FUN_180d9d940(0);
      }
      lVar2 = *(longlong *)(*(longlong *)(lVar2 + 0x10) + 0x20 + (longlong)(int)uVar1 * 8);
      if (lVar2 != 0) {
        uVar7 = FUN_1802fc120(lVar2,0);
        FUN_180433fa0(param_2,uVar7,0);
        if (*(longlong *)(param_1 + 0x70) != *(longlong *)(param_1 + 0x68)) {
          return;
        }
        if (param_3 == '\0') {
          return;
        }
        if (param_4 == 0) {
          if ((*(longlong *)(param_1 + 0x30) == 0) ||
             (lVar8 = *(longlong *)(*(longlong *)(param_1 + 0x30) + 0x18), lVar8 == 0)) {
            uVar7 = 0;
          }
          else {
            uVar7 = FUN_181105ca0(lVar2,0);
            uVar6 = FUN_180434850(lVar8,uVar7,0);
            local_res10 = 0;
            FUN_180ebc4b0(&local_res10,uVar6,DAT_182302de8);
            uVar7 = local_res10;
          }
          param_4 = (int)uVar7;
          if ((char)((ulonglong)uVar7 >> 0x20) == '\0') {
            param_4 = 0;
          }
        }
        if (param_4 == 1) {
          if (*(longlong *)(param_1 + 0x30) == 0) {
            return;
          }
          lVar8 = *(longlong *)(*(longlong *)(param_1 + 0x30) + 0x18);
          if (lVar8 == 0) {
            return;
          }
          uVar7 = FUN_181105ca0(lVar2,0);
          uVar9 = 0;
        }
        else {
          if (param_4 != 2) {
            return;
          }
          if (*(longlong *)(param_1 + 0x30) == 0) {
            return;
          }
          lVar8 = *(longlong *)(*(longlong *)(param_1 + 0x30) + 0x18);
          if (lVar8 == 0) {
            return;
          }
          uVar7 = FUN_181105ca0(lVar2,0);
          uVar9 = 1;
        }
        FUN_180434c70(lVar8,uVar7,uVar9,0);
        return;
      }
    }
  }
  FUN_18023bd10();
  pcVar3 = (code *)swi(3);
  (*pcVar3)();
  return;
}



/********************************************************************/
/* AbilityContentListController$$SetDescriptionText
 * RVA: 0x685930
 * Address: 0x180685930
 *******************************************************************/


void FUN_180685930(longlong param_1,uint param_2)

{
  longlong lVar1;
  code *pcVar2;
  char cVar3;
  longlong lVar4;
  longlong lVar5;
  undefined8 uVar6;
  undefined8 uVar7;
  
  if (DAT_181fedf7a == '\0') {
    thunk_FUN_180203190(DAT_1817caa78);
    DAT_181fedf7a = '\x01';
  }
  lVar4 = *(longlong *)(param_1 + 0x70);
  if (lVar4 == 0) goto LAB_180685bc0;
  if ((int)param_2 < *(int *)(lVar4 + 0x18)) {
    if (lVar4 == *(longlong *)(param_1 + 0x60)) {
      lVar4 = *(longlong *)(param_1 + 0x38);
      if (lVar4 == 0) goto LAB_180685bc0;
      if (*(int *)(lVar4 + 0x18) <= (int)param_2) {
        return;
      }
      lVar1 = *(longlong *)(param_1 + 0x30);
      uVar7 = 0;
      if (lVar1 != 0) {
        if (((*(byte *)(DAT_1822fcdd0 + 0x12f) & 2) != 0) && (*(int *)(DAT_1822fcdd0 + 0xe0) == 0))
        {
          il2cpp_runtime_class_init();
        }
        lVar4 = FUN_180f6c390(DAT_1822d9378);
        if (*(longlong *)(param_1 + 0x38) == 0) goto LAB_180685bc0;
        lVar5 = FUN_1800ddc20(*(longlong *)(param_1 + 0x38),param_2,DAT_1822a7c68);
        uVar6 = uVar7;
        if (lVar5 != 0) {
          uVar6 = FUN_180664300(lVar5,0);
        }
        if (lVar4 == 0) goto LAB_180685bc0;
        uVar6 = FUN_1802c0ff0(lVar4,uVar6,1,0);
        FUN_1815a02a0(*(undefined8 *)(lVar1 + 0x48),uVar6,0);
        lVar4 = *(longlong *)(param_1 + 0x38);
        if (lVar4 == 0) goto LAB_180685bc0;
      }
      if (*(uint *)(lVar4 + 0x18) <= param_2) {
        FUN_180d9d940(0);
      }
      lVar4 = *(longlong *)(*(longlong *)(lVar4 + 0x10) + 0x20 + (longlong)(int)param_2 * 8);
      if (lVar4 != 0) {
        uVar7 = FUN_180664300(lVar4,0);
      }
    }
    else {
      lVar4 = *(longlong *)(param_1 + 0x40);
      if (lVar4 == 0) goto LAB_180685bc0;
      if (*(int *)(lVar4 + 0x18) <= (int)param_2) {
        return;
      }
      lVar1 = *(longlong *)(param_1 + 0x30);
      uVar7 = 0;
      if (lVar1 != 0) {
        if (((*(byte *)(DAT_1822fcdd0 + 0x12f) & 2) != 0) && (*(int *)(DAT_1822fcdd0 + 0xe0) == 0))
        {
          il2cpp_runtime_class_init();
        }
        lVar4 = FUN_180f6c390(DAT_1822d9378);
        if (*(longlong *)(param_1 + 0x40) == 0) {
LAB_180685bc0:
          FUN_18023bd10();
          pcVar2 = (code *)swi(3);
          (*pcVar2)();
          return;
        }
        lVar5 = FUN_1800ddc20(*(longlong *)(param_1 + 0x40),param_2,DAT_1822a7c20);
        uVar6 = uVar7;
        if (lVar5 != 0) {
          uVar6 = FUN_180669390(lVar5,0);
        }
        if (lVar4 == 0) goto LAB_180685bc0;
        uVar6 = FUN_1802c0ff0(lVar4,uVar6,1,0);
        FUN_1815a02a0(*(undefined8 *)(lVar1 + 0x48),uVar6,0);
        lVar4 = *(longlong *)(param_1 + 0x40);
        if (lVar4 == 0) goto LAB_180685bc0;
      }
      if (*(uint *)(lVar4 + 0x18) <= param_2) {
        FUN_180d9d940(0);
      }
      lVar4 = *(longlong *)(*(longlong *)(lVar4 + 0x10) + 0x20 + (longlong)(int)param_2 * 8);
      if (lVar4 != 0) {
        uVar7 = FUN_180669390(lVar4,0);
      }
    }
    cVar3 = FUN_18108d010(uVar7,0);
    lVar4 = *(longlong *)(param_1 + 0x30);
    if (cVar3 == '\0') {
      if (lVar4 == 0) {
        return;
      }
      uVar7 = 0;
      goto LAB_180685a84;
    }
  }
  else {
    if (*(longlong *)(param_1 + 0x30) == 0) {
      return;
    }
    FUN_1815a02a0(*(undefined8 *)(*(longlong *)(param_1 + 0x30) + 0x48),
                  **(undefined8 **)(DAT_1822ba110 + 0xb8),0);
    lVar4 = *(longlong *)(param_1 + 0x30);
  }
  if (lVar4 == 0) {
    return;
  }
  uVar7 = 1;
LAB_180685a84:
  FUN_18159fe20(*(undefined8 *)(lVar4 + 0x40),uVar7,0);
  return;
}



/********************************************************************/
/* AbilityContentListController$$SetFocus
 * RVA: 0x685E90
 * Address: 0x180685E90
 *******************************************************************/


void FUN_180685e90(longlong param_1,char param_2)

{
  uint uVar1;
  longlong lVar2;
  longlong lVar3;
  code *pcVar4;
  undefined8 uVar5;
  
  if (DAT_181fedf67 == '\0') {
    thunk_FUN_180203190(DAT_1817cab48);
    DAT_181fedf67 = '\x01';
  }
  lVar2 = *(longlong *)(param_1 + 0x50);
  lVar3 = *(longlong *)(param_1 + 0x60);
  if (param_2 == '\0') {
    if ((lVar2 != 0) && (lVar3 != 0)) {
      uVar1 = *(uint *)(lVar2 + 0x18);
      if (*(uint *)(lVar3 + 0x18) <= uVar1) {
        FUN_180d9d940(0);
      }
      lVar3 = *(longlong *)(*(longlong *)(lVar3 + 0x10) + 0x20 + (longlong)(int)uVar1 * 8);
      if (lVar3 != 0) {
        uVar5 = FUN_1802fc120(lVar3,0);
LAB_180685f41:
        FUN_180433fa0(lVar2,uVar5,0);
        if (*(longlong *)(param_1 + 0x50) != 0) {
          FUN_180433b60(*(longlong *)(param_1 + 0x50),param_2,0);
        }
        return;
      }
    }
  }
  else if ((lVar2 != 0) && (lVar3 != 0)) {
    uVar1 = *(uint *)(lVar2 + 0x18);
    if (*(uint *)(lVar3 + 0x18) <= uVar1) {
      FUN_180d9d940(0);
    }
    lVar3 = *(longlong *)(*(longlong *)(lVar3 + 0x10) + 0x20 + (longlong)(int)uVar1 * 8);
    if (lVar3 != 0) {
      uVar5 = FUN_1802fc130(lVar3,0);
      goto LAB_180685f41;
    }
  }
  FUN_18023bd10();
  pcVar4 = (code *)swi(3);
  (*pcVar4)();
  return;
}



/********************************************************************/
/* AbilityContentListController$$UpdateFocus
 * RVA: 0x686950
 * Address: 0x180686950
 *******************************************************************/


void FUN_180686950(longlong param_1,undefined8 param_2,undefined8 param_3,undefined8 param_4)

{
  code *pcVar1;
  char cVar2;
  longlong lVar3;
  undefined8 uVar4;
  undefined4 uVar5;
  undefined4 local_58;
  undefined4 uStack_54;
  undefined4 uStack_50;
  undefined4 uStack_4c;
  longlong local_48;
  undefined4 local_40;
  undefined4 uStack_3c;
  undefined4 uStack_38;
  undefined4 uStack_34;
  longlong local_30;
  
  if (DAT_181fedf6d == '\0') {
    thunk_FUN_180203190(DAT_1817cabdc);
    DAT_181fedf6d = '\x01';
  }
  lVar3 = *(longlong *)(param_1 + 0x60);
  if (*(longlong *)(param_1 + 0x70) == lVar3) {
    if (lVar3 != 0) {
      FUN_1810eb840(&local_40,lVar3,DAT_1822ad6c8);
      local_58 = local_40;
      uStack_54 = uStack_3c;
      uStack_50 = uStack_38;
      uStack_4c = uStack_34;
      local_48 = local_30;
      while (cVar2 = FUN_180a4ee80(&local_58,DAT_1822cc2d0), lVar3 = local_48, cVar2 != '\0') {
        if (local_48 == 0) goto LAB_180686d0f;
        if (((*(char *)(param_1 + 0xa0) == '\0') ||
            (cVar2 = FUN_1803e74b0(*(undefined8 *)(param_1 + 0x98),*(undefined8 *)(local_48 + 0x18),
                                   0), cVar2 != '\0')) || (*(char *)(param_1 + 0xa1) == '\0')) {
          if (((*(byte *)(DAT_1822fd8c0 + 0x12f) & 2) != 0) && (*(int *)(DAT_1822fd8c0 + 0xe0) == 0)
             ) {
            il2cpp_runtime_class_init(DAT_1822fd8c0);
          }
          uVar5 = **(undefined4 **)(DAT_1822fd8c0 + 0xb8);
        }
        else {
          if (((*(byte *)(DAT_1822fd8c0 + 0x12f) & 2) != 0) && (*(int *)(DAT_1822fd8c0 + 0xe0) == 0)
             ) {
            il2cpp_runtime_class_init(DAT_1822fd8c0);
          }
          uVar5 = *(undefined4 *)(*(longlong *)(DAT_1822fd8c0 + 0xb8) + 0x10);
        }
        FUN_1803bba80(lVar3,uVar5);
      }
      uVar5 = 0x7b;
      FUN_18026d8f0(&local_58,DAT_1822c0c28);
      if (*(longlong *)(param_1 + 0x50) != 0) {
        lVar3 = FUN_180763cb0(*(undefined8 *)(param_1 + 0x60),
                              *(undefined4 *)(*(longlong *)(param_1 + 0x50) + 0x18),DAT_1822b9780,
                              param_4,uVar5);
        if (lVar3 == 0) {
          uVar4 = 0;
        }
        else {
          uVar4 = *(undefined8 *)(lVar3 + 0x18);
        }
        if (param_1 != 0) {
          if ((*(char *)(param_1 + 0xa0) == '\0') ||
             (cVar2 = FUN_1803e74b0(*(undefined8 *)(param_1 + 0x98),uVar4,0), cVar2 != '\0')) {
            if (lVar3 == 0) {
              return;
            }
          }
          else {
            if (lVar3 == 0) {
              return;
            }
            if (*(char *)(param_1 + 0xa1) != '\0') {
              if (((*(byte *)(DAT_1822fd8c0 + 0x12f) & 2) != 0) &&
                 (*(int *)(DAT_1822fd8c0 + 0xe0) == 0)) {
                il2cpp_runtime_class_init(DAT_1822fd8c0);
              }
              uVar5 = *(undefined4 *)(*(longlong *)(DAT_1822fd8c0 + 0xb8) + 0x10);
              goto LAB_180686ce8;
            }
          }
          if (((*(byte *)(DAT_1822fd8c0 + 0x12f) & 2) != 0) && (*(int *)(DAT_1822fd8c0 + 0xe0) == 0)
             ) {
            il2cpp_runtime_class_init(DAT_1822fd8c0);
          }
          uVar5 = *(undefined4 *)(*(longlong *)(DAT_1822fd8c0 + 0xb8) + 8);
          goto LAB_180686ce8;
        }
      }
    }
  }
  else if (*(longlong *)(param_1 + 0x68) != 0) {
    FUN_1810eb840(&local_40,*(longlong *)(param_1 + 0x68),DAT_1822ad6c8);
    local_58 = local_40;
    uStack_54 = uStack_3c;
    uStack_50 = uStack_38;
    uStack_4c = uStack_34;
    local_48 = local_30;
    while (cVar2 = FUN_180a4ee80(&local_58,DAT_1822cc2d0), lVar3 = local_48, cVar2 != '\0') {
      if (((*(byte *)(DAT_1822fd8c0 + 0x12f) & 2) != 0) && (*(int *)(DAT_1822fd8c0 + 0xe0) == 0)) {
        il2cpp_runtime_class_init(DAT_1822fd8c0);
      }
      if (lVar3 == 0) goto LAB_180686d01;
      FUN_1803bba80(lVar3,**(undefined4 **)(DAT_1822fd8c0 + 0xb8),0);
    }
    uVar5 = 0x116;
    FUN_18026d8f0(&local_58,DAT_1822c0c28);
    if (*(longlong *)(param_1 + 0x50) != 0) {
      lVar3 = FUN_180763cb0(*(undefined8 *)(param_1 + 0x68),
                            *(undefined4 *)(*(longlong *)(param_1 + 0x50) + 0x18),DAT_1822b9780,
                            param_4,uVar5);
      if (((*(byte *)(DAT_1822fd8c0 + 0x12f) & 2) != 0) && (*(int *)(DAT_1822fd8c0 + 0xe0) == 0)) {
        il2cpp_runtime_class_init();
      }
      if (lVar3 != 0) {
        uVar5 = *(undefined4 *)(*(longlong *)(DAT_1822fd8c0 + 0xb8) + 8);
LAB_180686ce8:
        FUN_1803bba80(lVar3,uVar5,0);
        return;
      }
    }
  }
  FUN_18023bd10();
LAB_180686d01:
  uVar5 = FUN_18023bd10();
  FUN_18023bce0(uVar5,0);
LAB_180686d0f:
  uVar5 = FUN_18023bd10();
  FUN_18023bce0(uVar5,0);
  pcVar1 = (code *)swi(3);
  (*pcVar1)();
  return;
}



/********************************************************************/
/* AbilityContentListController$$UpdateOwnsAbilityList
 * RVA: 0x686D20
 * Address: 0x180686D20
 *******************************************************************/


void FUN_180686d20(longlong param_1,undefined8 param_2,char param_3)

{
  undefined8 uVar1;
  code *pcVar2;
  char cVar3;
  int iVar4;
  longlong lVar5;
  undefined8 uVar6;
  longlong lVar7;
  longlong *plVar8;
  undefined4 local_60;
  undefined4 uStack_5c;
  undefined4 uStack_58;
  undefined4 uStack_54;
  undefined8 local_50;
  undefined4 local_48;
  undefined4 uStack_44;
  undefined4 uStack_40;
  undefined4 uStack_3c;
  undefined8 local_38;
  
  if (DAT_181fedf69 == '\0') {
    thunk_FUN_180203190(DAT_1817cabf0);
    DAT_181fedf69 = '\x01';
  }
  if ((param_3 == '\0') && (*(longlong *)(param_1 + 0x30) != 0)) {
    FUN_18159fe20(*(undefined8 *)(*(longlong *)(param_1 + 0x30) + 0x20),0,0);
  }
  if (*(longlong *)(param_1 + 0x30) != 0) {
    FUN_180687d20(*(longlong *)(param_1 + 0x30),1,0);
  }
  if (((*(byte *)(DAT_1822fc4e0 + 0x12f) & 2) != 0) && (*(int *)(DAT_1822fc4e0 + 0xe0) == 0)) {
    il2cpp_runtime_class_init();
  }
  lVar5 = FUN_180645130(0);
  if (lVar5 != 0) {
    uVar6 = FUN_180684430(param_1,param_2,*(undefined8 *)(lVar5 + 0x28),0);
    *(undefined8 *)(param_1 + 0x40) = uVar6;
    thunk_FUN_180239040(param_1 + 0x40,uVar6);
    uVar6 = FUN_1806842c0(param_1,0);
    *(undefined8 *)(param_1 + 0x48) = uVar6;
    thunk_FUN_180239040((undefined8 *)(param_1 + 0x48),uVar6);
    if (*(longlong *)(param_1 + 0x30) != 0) {
      FUN_18159fd20(*(undefined8 *)(*(longlong *)(param_1 + 0x30) + 0x50),0,0);
    }
    uVar6 = *(undefined8 *)(param_1 + 0x40);
    if (((*(byte *)(DAT_1822c4968 + 0x12f) & 2) != 0) && (*(int *)(DAT_1822c4968 + 0xe0) == 0)) {
      il2cpp_runtime_class_init();
    }
    lVar5 = *(longlong *)(*(longlong *)(DAT_1822c4968 + 0xb8) + 0x10);
    if (lVar5 == 0) {
      if (((*(byte *)(DAT_1822c4968 + 0x12f) & 2) != 0) && (*(int *)(DAT_1822c4968 + 0xe0) == 0)) {
        il2cpp_runtime_class_init();
      }
      uVar1 = **(undefined8 **)(DAT_1822c4968 + 0xb8);
      lVar5 = thunk_FUN_180207de0(DAT_1822faf20);
      FUN_1802e9aa0(lVar5,uVar1,DAT_1822e0df8,DAT_1822a79c0);
      plVar8 = (longlong *)(*(longlong *)(DAT_1822c4968 + 0xb8) + 0x10);
      *plVar8 = lVar5;
      thunk_FUN_180239040(plVar8,lVar5);
    }
    iVar4 = FUN_180bda680(uVar6,lVar5,DAT_1822f3ae0);
    lVar5 = *(longlong *)(param_1 + 0x30);
    if (iVar4 == 0) {
      *(undefined *)(param_1 + 0x29) = 0;
      if (lVar5 != 0) {
        FUN_18159fe20(*(undefined8 *)(lVar5 + 0x30),0,0);
        if (*(longlong *)(param_1 + 0x30) != 0) {
          FUN_18159fd20(*(undefined8 *)(*(longlong *)(param_1 + 0x30) + 0x58),1,0);
        }
      }
    }
    else {
      *(undefined *)(param_1 + 0x29) = 1;
      if (lVar5 != 0) {
        FUN_18159fe20(*(undefined8 *)(lVar5 + 0x30),1,0);
        if (*(longlong *)(param_1 + 0x30) != 0) {
          FUN_18159fd20(*(undefined8 *)(*(longlong *)(param_1 + 0x30) + 0x58),0,0);
          if ((*(longlong *)(param_1 + 0x30) != 0) &&
             (lVar5 = *(longlong *)(*(longlong *)(param_1 + 0x30) + 0x18), lVar5 != 0)) {
            FUN_180434c40(lVar5,0);
          }
        }
      }
    }
    if (*(longlong *)(param_1 + 0x68) != 0) {
      FUN_1810eb840(&local_48,*(longlong *)(param_1 + 0x68),DAT_1822ad6c8);
      local_60 = local_48;
      uStack_5c = uStack_44;
      uStack_58 = uStack_40;
      uStack_54 = uStack_3c;
      local_50 = local_38;
      while (cVar3 = FUN_180a4ee80(&local_60,DAT_1822cc2d0), cVar3 != '\0') {
        FUN_18159fd20(local_50,0);
      }
      FUN_18026d8f0(&local_60);
      iVar4 = 0;
      lVar5 = *(longlong *)(param_1 + 0x40);
      while (lVar5 != 0) {
        if (*(int *)(lVar5 + 0x18) <= iVar4) {
          *(undefined8 *)(param_1 + 0x70) = *(undefined8 *)(param_1 + 0x68);
          thunk_FUN_180239040();
          lVar5 = *(longlong *)(param_1 + 0x50);
          if (DAT_181fedf77 == '\0') {
            thunk_FUN_180203190(DAT_1817ca9dc);
            DAT_181fedf77 = '\x01';
          }
          if (((*(byte *)(DAT_1822abb78 + 0x12f) & 2) != 0) && (*(int *)(DAT_1822abb78 + 0xe0) == 0)
             ) {
            il2cpp_runtime_class_init();
          }
          cVar3 = FUN_18105b7d0(lVar5,0,0);
          if (cVar3 == '\0') {
            FUN_180685750(param_1,lVar5,1,0,0);
            if (lVar5 == 0) break;
            FUN_180685930(param_1,*(undefined4 *)(lVar5 + 0x18),0);
          }
          return;
        }
        lVar5 = FUN_180763cb0(lVar5,iVar4,DAT_1822b9ae0);
        lVar7 = FUN_180763cb0(*(undefined8 *)(param_1 + 0x68),iVar4);
        if (((*(byte *)(DAT_1822abb78 + 0x12f) & 2) != 0) && (*(int *)(DAT_1822abb78 + 0xe0) == 0))
        {
          il2cpp_runtime_class_init();
        }
        cVar3 = FUN_18105b7d0(lVar7,0,0);
        if (cVar3 == '\0') {
          if (lVar5 == 0) {
            if (lVar7 == 0) break;
            uVar6 = 0;
          }
          else {
            FUN_18159fd20(lVar7,1);
            if (lVar7 == 0) break;
            uVar6 = 1;
          }
          FUN_1803bb960(lVar7,uVar6);
          FUN_1803bbb30(lVar7,lVar5);
        }
        iVar4 = iVar4 + 1;
        lVar5 = *(longlong *)(param_1 + 0x40);
      }
    }
  }
  FUN_18023bd10();
  pcVar2 = (code *)swi(3);
  (*pcVar2)();
  return;
}



/********************************************************************/
/* AbilityContentListController$$UpdateView
 * RVA: 0x687190
 * Address: 0x180687190
 *******************************************************************/


void FUN_180687190(longlong param_1,longlong param_2,byte param_3,char param_4)

{
  longlong *plVar1;
  undefined8 uVar2;
  longlong lVar3;
  code *pcVar4;
  byte bVar5;
  char cVar6;
  int iVar7;
  undefined4 uVar8;
  undefined8 uVar9;
  longlong lVar10;
  longlong lVar11;
  undefined4 extraout_var;
  longlong *plVar12;
  int iVar13;
  undefined4 local_res8 [2];
  undefined4 local_res18 [2];
  undefined4 local_res20 [2];
  
  if (DAT_181fedf68 == '\0') {
    thunk_FUN_180203190(DAT_1817cac28);
    DAT_181fedf68 = '\x01';
  }
  iVar13 = 0;
  *(byte *)(param_1 + 0xa1) = param_3;
  local_res18[0] = 0;
  local_res8[0] = 0;
  local_res20[0] = 0;
  if ((param_4 == '\0') && (*(longlong *)(param_1 + 0x30) != 0)) {
    FUN_18159fe20(*(undefined8 *)(*(longlong *)(param_1 + 0x30) + 0x30),0,0);
  }
  if (*(longlong *)(param_1 + 0x30) != 0) {
    FUN_180687d20(*(longlong *)(param_1 + 0x30),0,0);
  }
  plVar1 = (longlong *)(param_1 + 0x98);
  *plVar1 = param_2;
  thunk_FUN_180239040(plVar1,param_2);
  uVar9 = FUN_180684080(param_1,param_2,0);
  *(undefined8 *)(param_1 + 0x38) = uVar9;
  thunk_FUN_180239040(param_1 + 0x38,uVar9);
  if (*(longlong *)(param_1 + 0x30) != 0) {
    FUN_18159fd20(*(undefined8 *)(*(longlong *)(param_1 + 0x30) + 0x58),0,0);
  }
  uVar9 = *(undefined8 *)(param_1 + 0x38);
  if (((*(byte *)(DAT_1822c4968 + 0x12f) & 2) != 0) && (*(int *)(DAT_1822c4968 + 0xe0) == 0)) {
    il2cpp_runtime_class_init();
  }
  lVar10 = *(longlong *)(*(longlong *)(DAT_1822c4968 + 0xb8) + 8);
  if (lVar10 == 0) {
    if (((*(byte *)(DAT_1822c4968 + 0x12f) & 2) != 0) && (*(int *)(DAT_1822c4968 + 0xe0) == 0)) {
      il2cpp_runtime_class_init();
    }
    uVar2 = **(undefined8 **)(DAT_1822c4968 + 0xb8);
    lVar10 = thunk_FUN_180207de0(DAT_1822fb178);
    FUN_1802e9aa0(lVar10,uVar2,DAT_1822e0de0,DAT_1822a7bc0);
    plVar12 = (longlong *)(*(longlong *)(DAT_1822c4968 + 0xb8) + 8);
    *plVar12 = lVar10;
    thunk_FUN_180239040(plVar12,lVar10);
  }
  iVar7 = FUN_180bda680(uVar9,lVar10,DAT_1822f3b60);
  lVar10 = *(longlong *)(param_1 + 0x30);
  if (iVar7 == 0) {
    *(undefined *)(param_1 + 0x28) = 0;
    if (lVar10 == 0) goto LAB_18068736d;
    FUN_18159fe20(*(undefined8 *)(lVar10 + 0x20),0,0);
    lVar10 = *(longlong *)(param_1 + 0x30);
    if (lVar10 == 0) goto LAB_18068736d;
    uVar9 = 1;
  }
  else {
    *(undefined *)(param_1 + 0x28) = 1;
    if (lVar10 == 0) goto LAB_18068736d;
    FUN_18159fe20(*(undefined8 *)(lVar10 + 0x20),1,0);
    lVar10 = *(longlong *)(param_1 + 0x30);
    if (lVar10 == 0) goto LAB_18068736d;
    uVar9 = 0;
  }
  FUN_18159fd20(*(undefined8 *)(lVar10 + 0x50),uVar9,0);
LAB_18068736d:
  iVar7 = 0;
  lVar10 = *(longlong *)(param_1 + 0x78);
  while (lVar10 != 0) {
    if (*(int *)(lVar10 + 0x18) <= iVar7) {
      lVar10 = *(longlong *)(param_1 + 0x38);
      goto joined_r0x000180687527;
    }
    lVar10 = FUN_180763cb0(lVar10,iVar7);
    if ((*plVar1 != 0) &&
       (lVar11 = FUN_180763cb0(*(undefined8 *)(*plVar1 + 0x20),iVar7), lVar11 != 0)) {
      local_res20[0] = FUN_180663f60(lVar11,0);
      uVar9 = FUN_180dee8e0(local_res20,0);
      if (lVar10 == 0) break;
      FUN_1803ba830(lVar10,uVar9,0);
      if (*plVar1 == 0) {
        local_res18[0] = 0;
LAB_18068745d:
        local_res8[0] = 0;
      }
      else {
        lVar3 = *(longlong *)(*plVar1 + 0x78);
        if (lVar3 == 0) break;
        FUN_1807632f0(*(undefined8 *)(lVar3 + 0x158),iVar7,DAT_1822b8248);
        local_res18[0] = extraout_var;
        if (*plVar1 == 0) goto LAB_18068745d;
        lVar3 = *(longlong *)(*plVar1 + 0x78);
        uVar8 = FUN_180663f60(lVar11,0);
        if (lVar3 == 0) break;
        local_res8[0] = FUN_180a81bf0(lVar3,uVar8,0);
      }
      bVar5 = FUN_1806636f0(lVar11,0);
      if ((param_3 & bVar5) == 0) {
        if (((*(byte *)(DAT_1822fd8c0 + 0x12f) & 2) != 0) && (*(int *)(DAT_1822fd8c0 + 0xe0) == 0))
        {
          il2cpp_runtime_class_init(DAT_1822fd8c0);
        }
        uVar8 = **(undefined4 **)(DAT_1822fd8c0 + 0xb8);
      }
      else {
        if (((*(byte *)(DAT_1822fd8c0 + 0x12f) & 2) != 0) && (*(int *)(DAT_1822fd8c0 + 0xe0) == 0))
        {
          il2cpp_runtime_class_init(DAT_1822fd8c0);
        }
        uVar8 = *(undefined4 *)(*(longlong *)(DAT_1822fd8c0 + 0xb8) + 0x10);
      }
      FUN_1803ba700(lVar10,uVar8,0);
      uVar9 = FUN_180dee8e0(local_res18,0);
      FUN_180dee8e0(local_res8,0);
      FUN_1803ba7e0(lVar10,uVar9);
    }
    iVar7 = iVar7 + 1;
    lVar10 = *(longlong *)(param_1 + 0x78);
  }
LAB_18068769e:
  FUN_18023bd10();
  pcVar4 = (code *)swi(3);
  (*pcVar4)();
  return;
joined_r0x000180687527:
  if (lVar10 == 0) goto LAB_18068769e;
  if (*(int *)(lVar10 + 0x18) <= iVar13) {
    *(undefined8 *)(param_1 + 0x70) = *(undefined8 *)(param_1 + 0x60);
    thunk_FUN_180239040();
    FUN_1806856b0(param_1,*(undefined8 *)(param_1 + 0x50),0);
    return;
  }
  lVar10 = FUN_180763cb0(lVar10,iVar13,DAT_1822b9b80);
  lVar11 = FUN_180763cb0(*(undefined8 *)(param_1 + 0x60),iVar13);
  if (((*(byte *)(DAT_1822abb78 + 0x12f) & 2) != 0) && (*(int *)(DAT_1822abb78 + 0xe0) == 0)) {
    il2cpp_runtime_class_init();
  }
  cVar6 = FUN_18105b7d0(lVar11,0);
  if (cVar6 == '\0') {
    if (lVar11 == 0) goto LAB_18068769e;
    FUN_1803bb960(lVar11,lVar10 != 0,0);
    FUN_1803bbc30(lVar11,lVar10,1,0);
    if (*(longlong *)(lVar11 + 0x18) != 0) {
      if (*(char *)(param_1 + 0xa0) == '\0') {
        bVar5 = 1;
      }
      else {
        bVar5 = FUN_1803e74b0(*plVar1);
      }
      if ((param_3 & (bVar5 ^ 1)) == 0) {
        if (((*(byte *)(DAT_1822fd8c0 + 0x12f) & 2) != 0) && (*(int *)(DAT_1822fd8c0 + 0xe0) == 0))
        {
          il2cpp_runtime_class_init(DAT_1822fd8c0);
        }
        uVar8 = **(undefined4 **)(DAT_1822fd8c0 + 0xb8);
      }
      else {
        if (((*(byte *)(DAT_1822fd8c0 + 0x12f) & 2) != 0) && (*(int *)(DAT_1822fd8c0 + 0xe0) == 0))
        {
          il2cpp_runtime_class_init(DAT_1822fd8c0);
        }
        uVar8 = *(undefined4 *)(*(longlong *)(DAT_1822fd8c0 + 0xb8) + 0x10);
      }
      FUN_1803bba80(lVar11,uVar8);
    }
  }
  lVar10 = *(longlong *)(param_1 + 0x38);
  iVar13 = iVar13 + 1;
  goto joined_r0x000180687527;
}



/====================================================================/
/* AbilityWindowController
 ===================================================================/

/********************************************************************/
/* AbilityWindowController$$SelectContent
 * RVA: 0x689120
 * Address: 0x180689120
 *******************************************************************/


void AbilityWindowController_SelectContent(void)

{
  code *pcVar1;
  undefined8 uVar2;
  
  uVar2 = thunk_FUN_1801f6190();
  FUN_18023bce0(uVar2,0);
  pcVar1 = (code *)swi(3);
  (*pcVar1)();
  return;
}



/********************************************************************/
/* AbilityWindowController$$UpdateView
 * RVA: 0x688450
 * Address: 0x180688450
 *******************************************************************/

/* DECOMPILATION FAILED: Could not create function at 0x180688450 */

/====================================================================/
/* BattleAbilityInfomationContentController
 ===================================================================/

/********************************************************************/
/* BattleAbilityInfomationContentController$$Initalize
 * RVA: 0x3BB7C0
 * Address: 0x1803BB7C0
 *******************************************************************/


void FUN_1803bb7c0(longlong param_1)

{
  longlong lVar1;
  
  lVar1 = *(longlong *)(param_1 + 0x30);
  if (lVar1 != 0) {
    FUN_1803bbd90(lVar1,0);
    FUN_18159fd20(*(undefined8 *)(lVar1 + 0x30),1,0);
    FUN_180533960(*(undefined8 *)(lVar1 + 0x50),0);
    return;
  }
  return;
}



/********************************************************************/
/* BattleAbilityInfomationContentController$$SetFocus
 * RVA: 0x3BB980
 * Address: 0x1803BB980
 *******************************************************************/


void FUN_1803bb980(longlong param_1,char param_2)

{
  undefined4 uVar1;
  longlong lVar2;
  
  if (DAT_181feaab7 == '\0') {
    thunk_FUN_180203190(DAT_181854ab0);
    DAT_181feaab7 = '\x01';
  }
  lVar2 = *(longlong *)(param_1 + 0x30);
  if (param_2 == '\0') {
    if (lVar2 == 0) {
      return;
    }
    if (((*(byte *)(DAT_1822fd8c0 + 0x12f) & 2) != 0) && (*(int *)(DAT_1822fd8c0 + 0xe0) == 0)) {
      il2cpp_runtime_class_init(DAT_1822fd8c0);
    }
    uVar1 = **(undefined4 **)(DAT_1822fd8c0 + 0xb8);
  }
  else {
    if (lVar2 == 0) {
      return;
    }
    if (((*(byte *)(DAT_1822fd8c0 + 0x12f) & 2) != 0) && (*(int *)(DAT_1822fd8c0 + 0xe0) == 0)) {
      il2cpp_runtime_class_init(DAT_1822fd8c0);
    }
    uVar1 = *(undefined4 *)(*(longlong *)(DAT_1822fd8c0 + 0xb8) + 8);
  }
  FUN_1803bc170(lVar2,uVar1,0);
  return;
}



/********************************************************************/
/* BattleAbilityInfomationContentController$$UpdateAbilitySkillLevel
 * RVA: 0x3BBAF0
 * Address: 0x1803BBAF0
 *******************************************************************/


void BattleAbilityInfomationContentController_UpdateAbilitySkillLevel
               (longlong param_1,longlong param_2)

{
  undefined4 uVar1;
  longlong lVar2;
  
  if (param_2 != 0) {
    uVar1 = FUN_1806643a0(param_2,0);
    lVar2 = *(longlong *)(param_1 + 0x30);
    if (lVar2 != 0) {
      lVar2 = *(longlong *)(lVar2 + 0x50);
    }
    FUN_180733c30(uVar1,lVar2,*(undefined8 *)(param_1 + 0x38),0);
  }
  return;
}



/********************************************************************/
/* BattleAbilityInfomationContentController$$UpdateView_OwnedAbility
 * RVA: 0x3BBC30
 * Address: 0x1803BBC30
 *******************************************************************/


void FUN_1803bbc30(longlong param_1,longlong param_2,undefined param_3)

{
  longlong lVar1;
  code *pcVar2;
  longlong lVar3;
  undefined8 uVar4;
  undefined8 uVar5;
  undefined4 local_res8 [2];
  
  if (DAT_181feaab8 == '\0') {
    thunk_FUN_180203190(DAT_181854b6c);
    DAT_181feaab8 = '\x01';
  }
  uVar5 = 0;
  *(longlong *)(param_1 + 0x18) = param_2;
  local_res8[0] = 0;
  thunk_FUN_180239040((longlong *)(param_1 + 0x18),param_2);
  if (param_2 != 0) {
    if (((*(byte *)(DAT_1822fcdd0 + 0x12f) & 2) != 0) && (*(int *)(DAT_1822fcdd0 + 0xe0) == 0)) {
      il2cpp_runtime_class_init();
    }
    lVar3 = FUN_180f6c390(DAT_1822d9378);
    lVar1 = *(longlong *)(param_1 + 0x30);
    if (lVar1 != 0) {
      uVar4 = FUN_180664350(param_2,0);
      if (lVar3 == 0) {
        FUN_18023bd10();
        pcVar2 = (code *)swi(3);
        (*pcVar2)();
        return;
      }
      uVar4 = FUN_1802c0ff0(lVar3,uVar4,1,0);
      FUN_1803bc0c0(lVar1,uVar4,0);
      lVar1 = *(longlong *)(param_1 + 0x30);
      if (lVar1 != 0) {
        FUN_18159fd20(*(undefined8 *)(lVar1 + 0x40),param_3,0);
        FUN_18159fd20(*(undefined8 *)(lVar1 + 0x48),param_3,0);
        lVar1 = *(longlong *)(param_1 + 0x30);
        if (lVar1 != 0) {
          if (*(longlong *)(param_2 + 0x10) != 0) {
            local_res8[0] = FUN_180a7dd30(*(longlong *)(param_2 + 0x10),0);
            uVar5 = FUN_180dee8e0(local_res8,0);
          }
          FUN_1815a02a0(*(undefined8 *)(lVar1 + 0x48),uVar5,0);
        }
      }
    }
  }
  return;
}



/====================================================================/
/* OwnedAbility
 ===================================================================/

/********************************************************************/
/* OwnedAbility$$get_Ability
 * RVA: 0x276F50
 * Address: 0x180276F50
 *******************************************************************/


undefined8 FUN_180276f50(longlong param_1)

{
  return *(undefined8 *)(param_1 + 0x10);
}



/********************************************************************/
/* OwnedAbility$$get_MesIdDescription
 * RVA: 0x664300
 * Address: 0x180664300
 *******************************************************************/


longlong FUN_180664300(longlong param_1)

{
  longlong lVar1;
  
  if (DAT_181fede0a == '\0') {
    thunk_FUN_180203190(DAT_181850f10);
    DAT_181fede0a = '\x01';
  }
  if ((*(longlong *)(param_1 + 0x18) != 0) &&
     (lVar1 = FUN_180a8a1b0(*(longlong *)(param_1 + 0x18),0), lVar1 != 0)) {
    return lVar1;
  }
  return **(longlong **)(DAT_1822ba110 + 0xb8);
}



/********************************************************************/
/* OwnedAbility$$get_MesIdName
 * RVA: 0x664350
 * Address: 0x180664350
 *******************************************************************/


longlong FUN_180664350(longlong param_1)

{
  longlong lVar1;
  
  if (DAT_181fede09 == '\0') {
    thunk_FUN_180203190(DAT_181850f24);
    DAT_181fede09 = '\x01';
  }
  if ((*(longlong *)(param_1 + 0x18) != 0) &&
     (lVar1 = FUN_180a87aa0(*(longlong *)(param_1 + 0x18),0), lVar1 != 0)) {
    return lVar1;
  }
  return **(longlong **)(DAT_1822ba110 + 0xb8);
}



/********************************************************************/
/* OwnedAbility$$get_SkillLevel
 * RVA: 0x6643A0
 * Address: 0x1806643A0
 *******************************************************************/


ulonglong FUN_1806643a0(longlong param_1)

{
  ulonglong uVar1;
  
  uVar1 = *(ulonglong *)(param_1 + 0x20);
  if (uVar1 != 0) {
    return (ulonglong)*(uint *)(uVar1 + 0x18);
  }
  return uVar1;
}

